// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pathways.proto

package org.mobilitydata.gtfsproto;

public final class PathwaysProto {
  private PathwaysProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PathwayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pathways.Pathway)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string pathway_id = 1;</code>
     */
    java.lang.String getPathwayId();
    /**
     * <code>string pathway_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getPathwayIdBytes();

    /**
     * <code>string from_stop_id = 2;</code>
     */
    java.lang.String getFromStopId();
    /**
     * <code>string from_stop_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getFromStopIdBytes();

    /**
     * <code>string to_stop_id = 3;</code>
     */
    java.lang.String getToStopId();
    /**
     * <code>string to_stop_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getToStopIdBytes();

    /**
     * <code>.pathways.Pathway.PathwayMode pathway_mode = 4;</code>
     */
    int getPathwayModeValue();
    /**
     * <code>.pathways.Pathway.PathwayMode pathway_mode = 4;</code>
     */
    PathwaysProto.Pathway.PathwayMode getPathwayMode();

    /**
     * <code>.pathways.Pathway.IsBidirectional is_bidirectional = 5;</code>
     */
    int getIsBidirectionalValue();
    /**
     * <code>.pathways.Pathway.IsBidirectional is_bidirectional = 5;</code>
     */
    PathwaysProto.Pathway.IsBidirectional getIsBidirectional();

    /**
     * <code>float length = 6;</code>
     */
    float getLength();

    /**
     * <code>uint32 traversal_time = 7;</code>
     */
    int getTraversalTime();

    /**
     * <code>int32 stair_count = 8;</code>
     */
    int getStairCount();

    /**
     * <code>float max_slope = 9;</code>
     */
    float getMaxSlope();

    /**
     * <pre>
     *must be positive
     * </pre>
     *
     * <code>float min_width = 10;</code>
     */
    float getMinWidth();

    /**
     * <code>string signposted_as = 11;</code>
     */
    java.lang.String getSignpostedAs();
    /**
     * <code>string signposted_as = 11;</code>
     */
    com.google.protobuf.ByteString
        getSignpostedAsBytes();

    /**
     * <code>string reversed_signposted_as = 12;</code>
     */
    java.lang.String getReversedSignpostedAs();
    /**
     * <code>string reversed_signposted_as = 12;</code>
     */
    com.google.protobuf.ByteString
        getReversedSignpostedAsBytes();
  }
  /**
   * Protobuf type {@code pathways.Pathway}
   */
  public  static final class Pathway extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pathways.Pathway)
      PathwayOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Pathway.newBuilder() to construct.
    private Pathway(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Pathway() {
      pathwayId_ = "";
      fromStopId_ = "";
      toStopId_ = "";
      pathwayMode_ = 0;
      isBidirectional_ = 0;
      signpostedAs_ = "";
      reversedSignpostedAs_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Pathway();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Pathway(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              pathwayId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              fromStopId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              toStopId_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              pathwayMode_ = rawValue;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              isBidirectional_ = rawValue;
              break;
            }
            case 53: {

              length_ = input.readFloat();
              break;
            }
            case 56: {

              traversalTime_ = input.readUInt32();
              break;
            }
            case 64: {

              stairCount_ = input.readInt32();
              break;
            }
            case 77: {

              maxSlope_ = input.readFloat();
              break;
            }
            case 85: {

              minWidth_ = input.readFloat();
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              signpostedAs_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              reversedSignpostedAs_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PathwaysProto.internal_static_pathways_Pathway_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PathwaysProto.internal_static_pathways_Pathway_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PathwaysProto.Pathway.class, PathwaysProto.Pathway.Builder.class);
    }

    /**
     * Protobuf enum {@code pathways.Pathway.PathwayMode}
     */
    public enum PathwayMode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *First enum value must be 0 in proto3
       * </pre>
       *
       * <code>RESERVED = 0;</code>
       */
      RESERVED(0),
      /**
       * <code>WALKWAY = 1;</code>
       */
      WALKWAY(1),
      /**
       * <code>STAIRS = 2;</code>
       */
      STAIRS(2),
      /**
       * <code>MOVING_SIDEWALK_TRAVELATOR = 3;</code>
       */
      MOVING_SIDEWALK_TRAVELATOR(3),
      /**
       * <code>ESCALATOR = 4;</code>
       */
      ESCALATOR(4),
      /**
       * <code>ELEVATOR = 5;</code>
       */
      ELEVATOR(5),
      /**
       * <code>FARE_GATE = 6;</code>
       */
      FARE_GATE(6),
      /**
       * <code>EXIT_GATE = 7;</code>
       */
      EXIT_GATE(7),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *First enum value must be 0 in proto3
       * </pre>
       *
       * <code>RESERVED = 0;</code>
       */
      public static final int RESERVED_VALUE = 0;
      /**
       * <code>WALKWAY = 1;</code>
       */
      public static final int WALKWAY_VALUE = 1;
      /**
       * <code>STAIRS = 2;</code>
       */
      public static final int STAIRS_VALUE = 2;
      /**
       * <code>MOVING_SIDEWALK_TRAVELATOR = 3;</code>
       */
      public static final int MOVING_SIDEWALK_TRAVELATOR_VALUE = 3;
      /**
       * <code>ESCALATOR = 4;</code>
       */
      public static final int ESCALATOR_VALUE = 4;
      /**
       * <code>ELEVATOR = 5;</code>
       */
      public static final int ELEVATOR_VALUE = 5;
      /**
       * <code>FARE_GATE = 6;</code>
       */
      public static final int FARE_GATE_VALUE = 6;
      /**
       * <code>EXIT_GATE = 7;</code>
       */
      public static final int EXIT_GATE_VALUE = 7;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PathwayMode valueOf(int value) {
        return forNumber(value);
      }

      public static PathwayMode forNumber(int value) {
        switch (value) {
          case 0: return RESERVED;
          case 1: return WALKWAY;
          case 2: return STAIRS;
          case 3: return MOVING_SIDEWALK_TRAVELATOR;
          case 4: return ESCALATOR;
          case 5: return ELEVATOR;
          case 6: return FARE_GATE;
          case 7: return EXIT_GATE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PathwayMode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PathwayMode> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PathwayMode>() {
              public PathwayMode findValueByNumber(int number) {
                return PathwayMode.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return PathwaysProto.Pathway.getDescriptor().getEnumTypes().get(0);
      }

      private static final PathwayMode[] VALUES = values();

      public static PathwayMode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PathwayMode(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pathways.Pathway.PathwayMode)
    }

    /**
     * Protobuf enum {@code pathways.Pathway.IsBidirectional}
     */
    public enum IsBidirectional
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *First enum value must be 0 in proto3
       * </pre>
       *
       * <code>FALSE = 0;</code>
       */
      FALSE(0),
      /**
       * <code>TRUE = 1;</code>
       */
      TRUE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *First enum value must be 0 in proto3
       * </pre>
       *
       * <code>FALSE = 0;</code>
       */
      public static final int FALSE_VALUE = 0;
      /**
       * <code>TRUE = 1;</code>
       */
      public static final int TRUE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static IsBidirectional valueOf(int value) {
        return forNumber(value);
      }

      public static IsBidirectional forNumber(int value) {
        switch (value) {
          case 0: return FALSE;
          case 1: return TRUE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<IsBidirectional>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          IsBidirectional> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<IsBidirectional>() {
              public IsBidirectional findValueByNumber(int number) {
                return IsBidirectional.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return PathwaysProto.Pathway.getDescriptor().getEnumTypes().get(1);
      }

      private static final IsBidirectional[] VALUES = values();

      public static IsBidirectional valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private IsBidirectional(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pathways.Pathway.IsBidirectional)
    }

    public static final int PATHWAY_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object pathwayId_;
    /**
     * <code>string pathway_id = 1;</code>
     */
    public java.lang.String getPathwayId() {
      java.lang.Object ref = pathwayId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pathwayId_ = s;
        return s;
      }
    }
    /**
     * <code>string pathway_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPathwayIdBytes() {
      java.lang.Object ref = pathwayId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pathwayId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROM_STOP_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object fromStopId_;
    /**
     * <code>string from_stop_id = 2;</code>
     */
    public java.lang.String getFromStopId() {
      java.lang.Object ref = fromStopId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromStopId_ = s;
        return s;
      }
    }
    /**
     * <code>string from_stop_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFromStopIdBytes() {
      java.lang.Object ref = fromStopId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromStopId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_STOP_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object toStopId_;
    /**
     * <code>string to_stop_id = 3;</code>
     */
    public java.lang.String getToStopId() {
      java.lang.Object ref = toStopId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toStopId_ = s;
        return s;
      }
    }
    /**
     * <code>string to_stop_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getToStopIdBytes() {
      java.lang.Object ref = toStopId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toStopId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATHWAY_MODE_FIELD_NUMBER = 4;
    private int pathwayMode_;
    /**
     * <code>.pathways.Pathway.PathwayMode pathway_mode = 4;</code>
     */
    public int getPathwayModeValue() {
      return pathwayMode_;
    }
    /**
     * <code>.pathways.Pathway.PathwayMode pathway_mode = 4;</code>
     */
    public PathwaysProto.Pathway.PathwayMode getPathwayMode() {
      @SuppressWarnings("deprecation")
      PathwaysProto.Pathway.PathwayMode result = PathwaysProto.Pathway.PathwayMode.valueOf(pathwayMode_);
      return result == null ? PathwaysProto.Pathway.PathwayMode.UNRECOGNIZED : result;
    }

    public static final int IS_BIDIRECTIONAL_FIELD_NUMBER = 5;
    private int isBidirectional_;
    /**
     * <code>.pathways.Pathway.IsBidirectional is_bidirectional = 5;</code>
     */
    public int getIsBidirectionalValue() {
      return isBidirectional_;
    }
    /**
     * <code>.pathways.Pathway.IsBidirectional is_bidirectional = 5;</code>
     */
    public PathwaysProto.Pathway.IsBidirectional getIsBidirectional() {
      @SuppressWarnings("deprecation")
      PathwaysProto.Pathway.IsBidirectional result = PathwaysProto.Pathway.IsBidirectional.valueOf(isBidirectional_);
      return result == null ? PathwaysProto.Pathway.IsBidirectional.UNRECOGNIZED : result;
    }

    public static final int LENGTH_FIELD_NUMBER = 6;
    private float length_;
    /**
     * <code>float length = 6;</code>
     */
    public float getLength() {
      return length_;
    }

    public static final int TRAVERSAL_TIME_FIELD_NUMBER = 7;
    private int traversalTime_;
    /**
     * <code>uint32 traversal_time = 7;</code>
     */
    public int getTraversalTime() {
      return traversalTime_;
    }

    public static final int STAIR_COUNT_FIELD_NUMBER = 8;
    private int stairCount_;
    /**
     * <code>int32 stair_count = 8;</code>
     */
    public int getStairCount() {
      return stairCount_;
    }

    public static final int MAX_SLOPE_FIELD_NUMBER = 9;
    private float maxSlope_;
    /**
     * <code>float max_slope = 9;</code>
     */
    public float getMaxSlope() {
      return maxSlope_;
    }

    public static final int MIN_WIDTH_FIELD_NUMBER = 10;
    private float minWidth_;
    /**
     * <pre>
     *must be positive
     * </pre>
     *
     * <code>float min_width = 10;</code>
     */
    public float getMinWidth() {
      return minWidth_;
    }

    public static final int SIGNPOSTED_AS_FIELD_NUMBER = 11;
    private volatile java.lang.Object signpostedAs_;
    /**
     * <code>string signposted_as = 11;</code>
     */
    public java.lang.String getSignpostedAs() {
      java.lang.Object ref = signpostedAs_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signpostedAs_ = s;
        return s;
      }
    }
    /**
     * <code>string signposted_as = 11;</code>
     */
    public com.google.protobuf.ByteString
        getSignpostedAsBytes() {
      java.lang.Object ref = signpostedAs_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signpostedAs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REVERSED_SIGNPOSTED_AS_FIELD_NUMBER = 12;
    private volatile java.lang.Object reversedSignpostedAs_;
    /**
     * <code>string reversed_signposted_as = 12;</code>
     */
    public java.lang.String getReversedSignpostedAs() {
      java.lang.Object ref = reversedSignpostedAs_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reversedSignpostedAs_ = s;
        return s;
      }
    }
    /**
     * <code>string reversed_signposted_as = 12;</code>
     */
    public com.google.protobuf.ByteString
        getReversedSignpostedAsBytes() {
      java.lang.Object ref = reversedSignpostedAs_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reversedSignpostedAs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPathwayIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pathwayId_);
      }
      if (!getFromStopIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fromStopId_);
      }
      if (!getToStopIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, toStopId_);
      }
      if (pathwayMode_ != PathwaysProto.Pathway.PathwayMode.RESERVED.getNumber()) {
        output.writeEnum(4, pathwayMode_);
      }
      if (isBidirectional_ != PathwaysProto.Pathway.IsBidirectional.FALSE.getNumber()) {
        output.writeEnum(5, isBidirectional_);
      }
      if (length_ != 0F) {
        output.writeFloat(6, length_);
      }
      if (traversalTime_ != 0) {
        output.writeUInt32(7, traversalTime_);
      }
      if (stairCount_ != 0) {
        output.writeInt32(8, stairCount_);
      }
      if (maxSlope_ != 0F) {
        output.writeFloat(9, maxSlope_);
      }
      if (minWidth_ != 0F) {
        output.writeFloat(10, minWidth_);
      }
      if (!getSignpostedAsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, signpostedAs_);
      }
      if (!getReversedSignpostedAsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, reversedSignpostedAs_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPathwayIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pathwayId_);
      }
      if (!getFromStopIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fromStopId_);
      }
      if (!getToStopIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, toStopId_);
      }
      if (pathwayMode_ != PathwaysProto.Pathway.PathwayMode.RESERVED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, pathwayMode_);
      }
      if (isBidirectional_ != PathwaysProto.Pathway.IsBidirectional.FALSE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, isBidirectional_);
      }
      if (length_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, length_);
      }
      if (traversalTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, traversalTime_);
      }
      if (stairCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, stairCount_);
      }
      if (maxSlope_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, maxSlope_);
      }
      if (minWidth_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, minWidth_);
      }
      if (!getSignpostedAsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, signpostedAs_);
      }
      if (!getReversedSignpostedAsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, reversedSignpostedAs_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PathwaysProto.Pathway)) {
        return super.equals(obj);
      }
      PathwaysProto.Pathway other = (PathwaysProto.Pathway) obj;

      if (!getPathwayId()
          .equals(other.getPathwayId())) return false;
      if (!getFromStopId()
          .equals(other.getFromStopId())) return false;
      if (!getToStopId()
          .equals(other.getToStopId())) return false;
      if (pathwayMode_ != other.pathwayMode_) return false;
      if (isBidirectional_ != other.isBidirectional_) return false;
      if (java.lang.Float.floatToIntBits(getLength())
          != java.lang.Float.floatToIntBits(
              other.getLength())) return false;
      if (getTraversalTime()
          != other.getTraversalTime()) return false;
      if (getStairCount()
          != other.getStairCount()) return false;
      if (java.lang.Float.floatToIntBits(getMaxSlope())
          != java.lang.Float.floatToIntBits(
              other.getMaxSlope())) return false;
      if (java.lang.Float.floatToIntBits(getMinWidth())
          != java.lang.Float.floatToIntBits(
              other.getMinWidth())) return false;
      if (!getSignpostedAs()
          .equals(other.getSignpostedAs())) return false;
      if (!getReversedSignpostedAs()
          .equals(other.getReversedSignpostedAs())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PATHWAY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPathwayId().hashCode();
      hash = (37 * hash) + FROM_STOP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getFromStopId().hashCode();
      hash = (37 * hash) + TO_STOP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getToStopId().hashCode();
      hash = (37 * hash) + PATHWAY_MODE_FIELD_NUMBER;
      hash = (53 * hash) + pathwayMode_;
      hash = (37 * hash) + IS_BIDIRECTIONAL_FIELD_NUMBER;
      hash = (53 * hash) + isBidirectional_;
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLength());
      hash = (37 * hash) + TRAVERSAL_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTraversalTime();
      hash = (37 * hash) + STAIR_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getStairCount();
      hash = (37 * hash) + MAX_SLOPE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMaxSlope());
      hash = (37 * hash) + MIN_WIDTH_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMinWidth());
      hash = (37 * hash) + SIGNPOSTED_AS_FIELD_NUMBER;
      hash = (53 * hash) + getSignpostedAs().hashCode();
      hash = (37 * hash) + REVERSED_SIGNPOSTED_AS_FIELD_NUMBER;
      hash = (53 * hash) + getReversedSignpostedAs().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PathwaysProto.Pathway parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PathwaysProto.Pathway parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PathwaysProto.Pathway parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PathwaysProto.Pathway parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PathwaysProto.Pathway parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PathwaysProto.Pathway parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PathwaysProto.Pathway parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PathwaysProto.Pathway parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PathwaysProto.Pathway parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PathwaysProto.Pathway parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PathwaysProto.Pathway parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PathwaysProto.Pathway parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PathwaysProto.Pathway prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pathways.Pathway}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pathways.Pathway)
        PathwaysProto.PathwayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PathwaysProto.internal_static_pathways_Pathway_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PathwaysProto.internal_static_pathways_Pathway_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PathwaysProto.Pathway.class, PathwaysProto.Pathway.Builder.class);
      }

      // Construct using org.mobilitydata.gtfsproto.PathwaysProto.Pathway.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pathwayId_ = "";

        fromStopId_ = "";

        toStopId_ = "";

        pathwayMode_ = 0;

        isBidirectional_ = 0;

        length_ = 0F;

        traversalTime_ = 0;

        stairCount_ = 0;

        maxSlope_ = 0F;

        minWidth_ = 0F;

        signpostedAs_ = "";

        reversedSignpostedAs_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PathwaysProto.internal_static_pathways_Pathway_descriptor;
      }

      @java.lang.Override
      public PathwaysProto.Pathway getDefaultInstanceForType() {
        return PathwaysProto.Pathway.getDefaultInstance();
      }

      @java.lang.Override
      public PathwaysProto.Pathway build() {
        PathwaysProto.Pathway result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PathwaysProto.Pathway buildPartial() {
        PathwaysProto.Pathway result = new PathwaysProto.Pathway(this);
        result.pathwayId_ = pathwayId_;
        result.fromStopId_ = fromStopId_;
        result.toStopId_ = toStopId_;
        result.pathwayMode_ = pathwayMode_;
        result.isBidirectional_ = isBidirectional_;
        result.length_ = length_;
        result.traversalTime_ = traversalTime_;
        result.stairCount_ = stairCount_;
        result.maxSlope_ = maxSlope_;
        result.minWidth_ = minWidth_;
        result.signpostedAs_ = signpostedAs_;
        result.reversedSignpostedAs_ = reversedSignpostedAs_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PathwaysProto.Pathway) {
          return mergeFrom((PathwaysProto.Pathway)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PathwaysProto.Pathway other) {
        if (other == PathwaysProto.Pathway.getDefaultInstance()) return this;
        if (!other.getPathwayId().isEmpty()) {
          pathwayId_ = other.pathwayId_;
          onChanged();
        }
        if (!other.getFromStopId().isEmpty()) {
          fromStopId_ = other.fromStopId_;
          onChanged();
        }
        if (!other.getToStopId().isEmpty()) {
          toStopId_ = other.toStopId_;
          onChanged();
        }
        if (other.pathwayMode_ != 0) {
          setPathwayModeValue(other.getPathwayModeValue());
        }
        if (other.isBidirectional_ != 0) {
          setIsBidirectionalValue(other.getIsBidirectionalValue());
        }
        if (other.getLength() != 0F) {
          setLength(other.getLength());
        }
        if (other.getTraversalTime() != 0) {
          setTraversalTime(other.getTraversalTime());
        }
        if (other.getStairCount() != 0) {
          setStairCount(other.getStairCount());
        }
        if (other.getMaxSlope() != 0F) {
          setMaxSlope(other.getMaxSlope());
        }
        if (other.getMinWidth() != 0F) {
          setMinWidth(other.getMinWidth());
        }
        if (!other.getSignpostedAs().isEmpty()) {
          signpostedAs_ = other.signpostedAs_;
          onChanged();
        }
        if (!other.getReversedSignpostedAs().isEmpty()) {
          reversedSignpostedAs_ = other.reversedSignpostedAs_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PathwaysProto.Pathway parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PathwaysProto.Pathway) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object pathwayId_ = "";
      /**
       * <code>string pathway_id = 1;</code>
       */
      public java.lang.String getPathwayId() {
        java.lang.Object ref = pathwayId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pathwayId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pathway_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPathwayIdBytes() {
        java.lang.Object ref = pathwayId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pathwayId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pathway_id = 1;</code>
       */
      public Builder setPathwayId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pathwayId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pathway_id = 1;</code>
       */
      public Builder clearPathwayId() {
        
        pathwayId_ = getDefaultInstance().getPathwayId();
        onChanged();
        return this;
      }
      /**
       * <code>string pathway_id = 1;</code>
       */
      public Builder setPathwayIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pathwayId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fromStopId_ = "";
      /**
       * <code>string from_stop_id = 2;</code>
       */
      public java.lang.String getFromStopId() {
        java.lang.Object ref = fromStopId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromStopId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string from_stop_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFromStopIdBytes() {
        java.lang.Object ref = fromStopId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromStopId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string from_stop_id = 2;</code>
       */
      public Builder setFromStopId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromStopId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string from_stop_id = 2;</code>
       */
      public Builder clearFromStopId() {
        
        fromStopId_ = getDefaultInstance().getFromStopId();
        onChanged();
        return this;
      }
      /**
       * <code>string from_stop_id = 2;</code>
       */
      public Builder setFromStopIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromStopId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object toStopId_ = "";
      /**
       * <code>string to_stop_id = 3;</code>
       */
      public java.lang.String getToStopId() {
        java.lang.Object ref = toStopId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toStopId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string to_stop_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getToStopIdBytes() {
        java.lang.Object ref = toStopId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toStopId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string to_stop_id = 3;</code>
       */
      public Builder setToStopId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toStopId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string to_stop_id = 3;</code>
       */
      public Builder clearToStopId() {
        
        toStopId_ = getDefaultInstance().getToStopId();
        onChanged();
        return this;
      }
      /**
       * <code>string to_stop_id = 3;</code>
       */
      public Builder setToStopIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toStopId_ = value;
        onChanged();
        return this;
      }

      private int pathwayMode_ = 0;
      /**
       * <code>.pathways.Pathway.PathwayMode pathway_mode = 4;</code>
       */
      public int getPathwayModeValue() {
        return pathwayMode_;
      }
      /**
       * <code>.pathways.Pathway.PathwayMode pathway_mode = 4;</code>
       */
      public Builder setPathwayModeValue(int value) {
        pathwayMode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.pathways.Pathway.PathwayMode pathway_mode = 4;</code>
       */
      public PathwaysProto.Pathway.PathwayMode getPathwayMode() {
        @SuppressWarnings("deprecation")
        PathwaysProto.Pathway.PathwayMode result = PathwaysProto.Pathway.PathwayMode.valueOf(pathwayMode_);
        return result == null ? PathwaysProto.Pathway.PathwayMode.UNRECOGNIZED : result;
      }
      /**
       * <code>.pathways.Pathway.PathwayMode pathway_mode = 4;</code>
       */
      public Builder setPathwayMode(PathwaysProto.Pathway.PathwayMode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        pathwayMode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.pathways.Pathway.PathwayMode pathway_mode = 4;</code>
       */
      public Builder clearPathwayMode() {
        
        pathwayMode_ = 0;
        onChanged();
        return this;
      }

      private int isBidirectional_ = 0;
      /**
       * <code>.pathways.Pathway.IsBidirectional is_bidirectional = 5;</code>
       */
      public int getIsBidirectionalValue() {
        return isBidirectional_;
      }
      /**
       * <code>.pathways.Pathway.IsBidirectional is_bidirectional = 5;</code>
       */
      public Builder setIsBidirectionalValue(int value) {
        isBidirectional_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.pathways.Pathway.IsBidirectional is_bidirectional = 5;</code>
       */
      public PathwaysProto.Pathway.IsBidirectional getIsBidirectional() {
        @SuppressWarnings("deprecation")
        PathwaysProto.Pathway.IsBidirectional result = PathwaysProto.Pathway.IsBidirectional.valueOf(isBidirectional_);
        return result == null ? PathwaysProto.Pathway.IsBidirectional.UNRECOGNIZED : result;
      }
      /**
       * <code>.pathways.Pathway.IsBidirectional is_bidirectional = 5;</code>
       */
      public Builder setIsBidirectional(PathwaysProto.Pathway.IsBidirectional value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        isBidirectional_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.pathways.Pathway.IsBidirectional is_bidirectional = 5;</code>
       */
      public Builder clearIsBidirectional() {
        
        isBidirectional_ = 0;
        onChanged();
        return this;
      }

      private float length_ ;
      /**
       * <code>float length = 6;</code>
       */
      public float getLength() {
        return length_;
      }
      /**
       * <code>float length = 6;</code>
       */
      public Builder setLength(float value) {
        
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float length = 6;</code>
       */
      public Builder clearLength() {
        
        length_ = 0F;
        onChanged();
        return this;
      }

      private int traversalTime_ ;
      /**
       * <code>uint32 traversal_time = 7;</code>
       */
      public int getTraversalTime() {
        return traversalTime_;
      }
      /**
       * <code>uint32 traversal_time = 7;</code>
       */
      public Builder setTraversalTime(int value) {
        
        traversalTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 traversal_time = 7;</code>
       */
      public Builder clearTraversalTime() {
        
        traversalTime_ = 0;
        onChanged();
        return this;
      }

      private int stairCount_ ;
      /**
       * <code>int32 stair_count = 8;</code>
       */
      public int getStairCount() {
        return stairCount_;
      }
      /**
       * <code>int32 stair_count = 8;</code>
       */
      public Builder setStairCount(int value) {
        
        stairCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 stair_count = 8;</code>
       */
      public Builder clearStairCount() {
        
        stairCount_ = 0;
        onChanged();
        return this;
      }

      private float maxSlope_ ;
      /**
       * <code>float max_slope = 9;</code>
       */
      public float getMaxSlope() {
        return maxSlope_;
      }
      /**
       * <code>float max_slope = 9;</code>
       */
      public Builder setMaxSlope(float value) {
        
        maxSlope_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float max_slope = 9;</code>
       */
      public Builder clearMaxSlope() {
        
        maxSlope_ = 0F;
        onChanged();
        return this;
      }

      private float minWidth_ ;
      /**
       * <pre>
       *must be positive
       * </pre>
       *
       * <code>float min_width = 10;</code>
       */
      public float getMinWidth() {
        return minWidth_;
      }
      /**
       * <pre>
       *must be positive
       * </pre>
       *
       * <code>float min_width = 10;</code>
       */
      public Builder setMinWidth(float value) {
        
        minWidth_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *must be positive
       * </pre>
       *
       * <code>float min_width = 10;</code>
       */
      public Builder clearMinWidth() {
        
        minWidth_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object signpostedAs_ = "";
      /**
       * <code>string signposted_as = 11;</code>
       */
      public java.lang.String getSignpostedAs() {
        java.lang.Object ref = signpostedAs_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          signpostedAs_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string signposted_as = 11;</code>
       */
      public com.google.protobuf.ByteString
          getSignpostedAsBytes() {
        java.lang.Object ref = signpostedAs_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signpostedAs_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string signposted_as = 11;</code>
       */
      public Builder setSignpostedAs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signpostedAs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string signposted_as = 11;</code>
       */
      public Builder clearSignpostedAs() {
        
        signpostedAs_ = getDefaultInstance().getSignpostedAs();
        onChanged();
        return this;
      }
      /**
       * <code>string signposted_as = 11;</code>
       */
      public Builder setSignpostedAsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        signpostedAs_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reversedSignpostedAs_ = "";
      /**
       * <code>string reversed_signposted_as = 12;</code>
       */
      public java.lang.String getReversedSignpostedAs() {
        java.lang.Object ref = reversedSignpostedAs_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reversedSignpostedAs_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reversed_signposted_as = 12;</code>
       */
      public com.google.protobuf.ByteString
          getReversedSignpostedAsBytes() {
        java.lang.Object ref = reversedSignpostedAs_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reversedSignpostedAs_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reversed_signposted_as = 12;</code>
       */
      public Builder setReversedSignpostedAs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reversedSignpostedAs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reversed_signposted_as = 12;</code>
       */
      public Builder clearReversedSignpostedAs() {
        
        reversedSignpostedAs_ = getDefaultInstance().getReversedSignpostedAs();
        onChanged();
        return this;
      }
      /**
       * <code>string reversed_signposted_as = 12;</code>
       */
      public Builder setReversedSignpostedAsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reversedSignpostedAs_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pathways.Pathway)
    }

    // @@protoc_insertion_point(class_scope:pathways.Pathway)
    private static final PathwaysProto.Pathway DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PathwaysProto.Pathway();
    }

    public static PathwaysProto.Pathway getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Pathway>
        PARSER = new com.google.protobuf.AbstractParser<Pathway>() {
      @java.lang.Override
      public Pathway parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Pathway(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Pathway> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pathway> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PathwaysProto.Pathway getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface pathwayCollectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pathways.pathwayCollection)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .pathways.Pathway pathways = 1;</code>
     */
    java.util.List<PathwaysProto.Pathway>
        getPathwaysList();
    /**
     * <code>repeated .pathways.Pathway pathways = 1;</code>
     */
    PathwaysProto.Pathway getPathways(int index);
    /**
     * <code>repeated .pathways.Pathway pathways = 1;</code>
     */
    int getPathwaysCount();
    /**
     * <code>repeated .pathways.Pathway pathways = 1;</code>
     */
    java.util.List<? extends PathwaysProto.PathwayOrBuilder>
        getPathwaysOrBuilderList();
    /**
     * <code>repeated .pathways.Pathway pathways = 1;</code>
     */
    PathwaysProto.PathwayOrBuilder getPathwaysOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pathways.pathwayCollection}
   */
  public  static final class pathwayCollection extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pathways.pathwayCollection)
      pathwayCollectionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use pathwayCollection.newBuilder() to construct.
    private pathwayCollection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private pathwayCollection() {
      pathways_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new pathwayCollection();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private pathwayCollection(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                pathways_ = new java.util.ArrayList<PathwaysProto.Pathway>();
                mutable_bitField0_ |= 0x00000001;
              }
              pathways_.add(
                  input.readMessage(PathwaysProto.Pathway.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          pathways_ = java.util.Collections.unmodifiableList(pathways_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PathwaysProto.internal_static_pathways_pathwayCollection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PathwaysProto.internal_static_pathways_pathwayCollection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PathwaysProto.pathwayCollection.class, PathwaysProto.pathwayCollection.Builder.class);
    }

    public static final int PATHWAYS_FIELD_NUMBER = 1;
    private java.util.List<PathwaysProto.Pathway> pathways_;
    /**
     * <code>repeated .pathways.Pathway pathways = 1;</code>
     */
    public java.util.List<PathwaysProto.Pathway> getPathwaysList() {
      return pathways_;
    }
    /**
     * <code>repeated .pathways.Pathway pathways = 1;</code>
     */
    public java.util.List<? extends PathwaysProto.PathwayOrBuilder>
        getPathwaysOrBuilderList() {
      return pathways_;
    }
    /**
     * <code>repeated .pathways.Pathway pathways = 1;</code>
     */
    public int getPathwaysCount() {
      return pathways_.size();
    }
    /**
     * <code>repeated .pathways.Pathway pathways = 1;</code>
     */
    public PathwaysProto.Pathway getPathways(int index) {
      return pathways_.get(index);
    }
    /**
     * <code>repeated .pathways.Pathway pathways = 1;</code>
     */
    public PathwaysProto.PathwayOrBuilder getPathwaysOrBuilder(
        int index) {
      return pathways_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < pathways_.size(); i++) {
        output.writeMessage(1, pathways_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < pathways_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, pathways_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PathwaysProto.pathwayCollection)) {
        return super.equals(obj);
      }
      PathwaysProto.pathwayCollection other = (PathwaysProto.pathwayCollection) obj;

      if (!getPathwaysList()
          .equals(other.getPathwaysList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPathwaysCount() > 0) {
        hash = (37 * hash) + PATHWAYS_FIELD_NUMBER;
        hash = (53 * hash) + getPathwaysList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PathwaysProto.pathwayCollection parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PathwaysProto.pathwayCollection parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PathwaysProto.pathwayCollection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PathwaysProto.pathwayCollection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PathwaysProto.pathwayCollection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PathwaysProto.pathwayCollection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PathwaysProto.pathwayCollection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PathwaysProto.pathwayCollection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PathwaysProto.pathwayCollection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PathwaysProto.pathwayCollection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PathwaysProto.pathwayCollection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PathwaysProto.pathwayCollection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PathwaysProto.pathwayCollection prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pathways.pathwayCollection}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pathways.pathwayCollection)
        PathwaysProto.pathwayCollectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PathwaysProto.internal_static_pathways_pathwayCollection_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PathwaysProto.internal_static_pathways_pathwayCollection_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PathwaysProto.pathwayCollection.class, PathwaysProto.pathwayCollection.Builder.class);
      }

      // Construct using org.mobilitydata.gtfsproto.PathwaysProto.pathwayCollection.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPathwaysFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (pathwaysBuilder_ == null) {
          pathways_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pathwaysBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PathwaysProto.internal_static_pathways_pathwayCollection_descriptor;
      }

      @java.lang.Override
      public PathwaysProto.pathwayCollection getDefaultInstanceForType() {
        return PathwaysProto.pathwayCollection.getDefaultInstance();
      }

      @java.lang.Override
      public PathwaysProto.pathwayCollection build() {
        PathwaysProto.pathwayCollection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PathwaysProto.pathwayCollection buildPartial() {
        PathwaysProto.pathwayCollection result = new PathwaysProto.pathwayCollection(this);
        int from_bitField0_ = bitField0_;
        if (pathwaysBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            pathways_ = java.util.Collections.unmodifiableList(pathways_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.pathways_ = pathways_;
        } else {
          result.pathways_ = pathwaysBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PathwaysProto.pathwayCollection) {
          return mergeFrom((PathwaysProto.pathwayCollection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PathwaysProto.pathwayCollection other) {
        if (other == PathwaysProto.pathwayCollection.getDefaultInstance()) return this;
        if (pathwaysBuilder_ == null) {
          if (!other.pathways_.isEmpty()) {
            if (pathways_.isEmpty()) {
              pathways_ = other.pathways_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePathwaysIsMutable();
              pathways_.addAll(other.pathways_);
            }
            onChanged();
          }
        } else {
          if (!other.pathways_.isEmpty()) {
            if (pathwaysBuilder_.isEmpty()) {
              pathwaysBuilder_.dispose();
              pathwaysBuilder_ = null;
              pathways_ = other.pathways_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pathwaysBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPathwaysFieldBuilder() : null;
            } else {
              pathwaysBuilder_.addAllMessages(other.pathways_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PathwaysProto.pathwayCollection parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PathwaysProto.pathwayCollection) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<PathwaysProto.Pathway> pathways_ =
        java.util.Collections.emptyList();
      private void ensurePathwaysIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          pathways_ = new java.util.ArrayList<PathwaysProto.Pathway>(pathways_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PathwaysProto.Pathway, PathwaysProto.Pathway.Builder, PathwaysProto.PathwayOrBuilder> pathwaysBuilder_;

      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public java.util.List<PathwaysProto.Pathway> getPathwaysList() {
        if (pathwaysBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pathways_);
        } else {
          return pathwaysBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public int getPathwaysCount() {
        if (pathwaysBuilder_ == null) {
          return pathways_.size();
        } else {
          return pathwaysBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public PathwaysProto.Pathway getPathways(int index) {
        if (pathwaysBuilder_ == null) {
          return pathways_.get(index);
        } else {
          return pathwaysBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public Builder setPathways(
          int index, PathwaysProto.Pathway value) {
        if (pathwaysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePathwaysIsMutable();
          pathways_.set(index, value);
          onChanged();
        } else {
          pathwaysBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public Builder setPathways(
          int index, PathwaysProto.Pathway.Builder builderForValue) {
        if (pathwaysBuilder_ == null) {
          ensurePathwaysIsMutable();
          pathways_.set(index, builderForValue.build());
          onChanged();
        } else {
          pathwaysBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public Builder addPathways(PathwaysProto.Pathway value) {
        if (pathwaysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePathwaysIsMutable();
          pathways_.add(value);
          onChanged();
        } else {
          pathwaysBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public Builder addPathways(
          int index, PathwaysProto.Pathway value) {
        if (pathwaysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePathwaysIsMutable();
          pathways_.add(index, value);
          onChanged();
        } else {
          pathwaysBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public Builder addPathways(
          PathwaysProto.Pathway.Builder builderForValue) {
        if (pathwaysBuilder_ == null) {
          ensurePathwaysIsMutable();
          pathways_.add(builderForValue.build());
          onChanged();
        } else {
          pathwaysBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public Builder addPathways(
          int index, PathwaysProto.Pathway.Builder builderForValue) {
        if (pathwaysBuilder_ == null) {
          ensurePathwaysIsMutable();
          pathways_.add(index, builderForValue.build());
          onChanged();
        } else {
          pathwaysBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public Builder addAllPathways(
          java.lang.Iterable<? extends PathwaysProto.Pathway> values) {
        if (pathwaysBuilder_ == null) {
          ensurePathwaysIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, pathways_);
          onChanged();
        } else {
          pathwaysBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public Builder clearPathways() {
        if (pathwaysBuilder_ == null) {
          pathways_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pathwaysBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public Builder removePathways(int index) {
        if (pathwaysBuilder_ == null) {
          ensurePathwaysIsMutable();
          pathways_.remove(index);
          onChanged();
        } else {
          pathwaysBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public PathwaysProto.Pathway.Builder getPathwaysBuilder(
          int index) {
        return getPathwaysFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public PathwaysProto.PathwayOrBuilder getPathwaysOrBuilder(
          int index) {
        if (pathwaysBuilder_ == null) {
          return pathways_.get(index);  } else {
          return pathwaysBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public java.util.List<? extends PathwaysProto.PathwayOrBuilder>
           getPathwaysOrBuilderList() {
        if (pathwaysBuilder_ != null) {
          return pathwaysBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pathways_);
        }
      }
      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public PathwaysProto.Pathway.Builder addPathwaysBuilder() {
        return getPathwaysFieldBuilder().addBuilder(
            PathwaysProto.Pathway.getDefaultInstance());
      }
      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public PathwaysProto.Pathway.Builder addPathwaysBuilder(
          int index) {
        return getPathwaysFieldBuilder().addBuilder(
            index, PathwaysProto.Pathway.getDefaultInstance());
      }
      /**
       * <code>repeated .pathways.Pathway pathways = 1;</code>
       */
      public java.util.List<PathwaysProto.Pathway.Builder>
           getPathwaysBuilderList() {
        return getPathwaysFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PathwaysProto.Pathway, PathwaysProto.Pathway.Builder, PathwaysProto.PathwayOrBuilder>
          getPathwaysFieldBuilder() {
        if (pathwaysBuilder_ == null) {
          pathwaysBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PathwaysProto.Pathway, PathwaysProto.Pathway.Builder, PathwaysProto.PathwayOrBuilder>(
                  pathways_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          pathways_ = null;
        }
        return pathwaysBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pathways.pathwayCollection)
    }

    // @@protoc_insertion_point(class_scope:pathways.pathwayCollection)
    private static final PathwaysProto.pathwayCollection DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PathwaysProto.pathwayCollection();
    }

    public static PathwaysProto.pathwayCollection getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<pathwayCollection>
        PARSER = new com.google.protobuf.AbstractParser<pathwayCollection>() {
      @java.lang.Override
      public pathwayCollection parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new pathwayCollection(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<pathwayCollection> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<pathwayCollection> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PathwaysProto.pathwayCollection getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pathways_Pathway_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pathways_Pathway_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pathways_pathwayCollection_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pathways_pathwayCollection_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016pathways.proto\022\010pathways\"\215\004\n\007Pathway\022\022" +
      "\n\npathway_id\030\001 \001(\t\022\024\n\014from_stop_id\030\002 \001(\t" +
      "\022\022\n\nto_stop_id\030\003 \001(\t\0223\n\014pathway_mode\030\004 \001" +
      "(\0162\035.pathways.Pathway.PathwayMode\022;\n\020is_" +
      "bidirectional\030\005 \001(\0162!.pathways.Pathway.I" +
      "sBidirectional\022\016\n\006length\030\006 \001(\002\022\026\n\016traver" +
      "sal_time\030\007 \001(\r\022\023\n\013stair_count\030\010 \001(\005\022\021\n\tm" +
      "ax_slope\030\t \001(\002\022\021\n\tmin_width\030\n \001(\002\022\025\n\rsig" +
      "nposted_as\030\013 \001(\t\022\036\n\026reversed_signposted_" +
      "as\030\014 \001(\t\"\217\001\n\013PathwayMode\022\014\n\010RESERVED\020\000\022\013" +
      "\n\007WALKWAY\020\001\022\n\n\006STAIRS\020\002\022\036\n\032MOVING_SIDEWA" +
      "LK_TRAVELATOR\020\003\022\r\n\tESCALATOR\020\004\022\014\n\010ELEVAT" +
      "OR\020\005\022\r\n\tFARE_GATE\020\006\022\r\n\tEXIT_GATE\020\007\"&\n\017Is" +
      "Bidirectional\022\t\n\005FALSE\020\000\022\010\n\004TRUE\020\001\"8\n\021pa" +
      "thwayCollection\022#\n\010pathways\030\001 \003(\0132\021.path" +
      "ways.PathwayB!\n\020org.mobilitydataB\rPathwa" +
      "ysProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pathways_Pathway_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pathways_Pathway_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pathways_Pathway_descriptor,
        new java.lang.String[] { "PathwayId", "FromStopId", "ToStopId", "PathwayMode", "IsBidirectional", "Length", "TraversalTime", "StairCount", "MaxSlope", "MinWidth", "SignpostedAs", "ReversedSignpostedAs", });
    internal_static_pathways_pathwayCollection_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pathways_pathwayCollection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pathways_pathwayCollection_descriptor,
        new java.lang.String[] { "Pathways", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
