// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stops.proto

package org.mobilitydata.gtfsproto;

public final class StopsProto {
  private StopsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StopOrBuilder extends
      // @@protoc_insertion_point(interface_extends:stops.Stop)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string code = 2;</code>
     */
    java.lang.String getCode();
    /**
     * <code>string code = 2;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string desc = 4;</code>
     */
    java.lang.String getDesc();
    /**
     * <code>string desc = 4;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <code>.google.type.LatLng lat_lng = 5;</code>
     */
    boolean hasLatLng();
    /**
     * <code>.google.type.LatLng lat_lng = 5;</code>
     */
    com.google.type.LatLng getLatLng();
    /**
     * <code>.google.type.LatLng lat_lng = 5;</code>
     */
    com.google.type.LatLngOrBuilder getLatLngOrBuilder();

    /**
     * <code>int64 zone_id = 6;</code>
     */
    long getZoneId();

    /**
     * <code>string url = 7;</code>
     */
    java.lang.String getUrl();
    /**
     * <code>string url = 7;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>.stops.Stop.LocationType location_type = 8;</code>
     */
    int getLocationTypeValue();
    /**
     * <code>.stops.Stop.LocationType location_type = 8;</code>
     */
    StopsProto.Stop.LocationType getLocationType();

    /**
     * <code>int64 parent_station = 9;</code>
     */
    long getParentStation();

    /**
     * <code>string timezone = 10;</code>
     */
    java.lang.String getTimezone();
    /**
     * <code>string timezone = 10;</code>
     */
    com.google.protobuf.ByteString
        getTimezoneBytes();

    /**
     * <code>.stops.Stop.WheelchairBoarding wheelchair_boarding = 11;</code>
     */
    int getWheelchairBoardingValue();
    /**
     * <code>.stops.Stop.WheelchairBoarding wheelchair_boarding = 11;</code>
     */
    StopsProto.Stop.WheelchairBoarding getWheelchairBoarding();

    /**
     * <code>int64 level_id = 12;</code>
     */
    long getLevelId();

    /**
     * <code>string platform_code = 13;</code>
     */
    java.lang.String getPlatformCode();
    /**
     * <code>string platform_code = 13;</code>
     */
    com.google.protobuf.ByteString
        getPlatformCodeBytes();
  }
  /**
   * Protobuf type {@code stops.Stop}
   */
  public  static final class Stop extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:stops.Stop)
      StopOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Stop.newBuilder() to construct.
    private Stop(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Stop() {
      code_ = "";
      name_ = "";
      desc_ = "";
      url_ = "";
      locationType_ = 0;
      timezone_ = "";
      wheelchairBoarding_ = 0;
      platformCode_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Stop();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Stop(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              code_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              desc_ = s;
              break;
            }
            case 42: {
              com.google.type.LatLng.Builder subBuilder = null;
              if (latLng_ != null) {
                subBuilder = latLng_.toBuilder();
              }
              latLng_ = input.readMessage(com.google.type.LatLng.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(latLng_);
                latLng_ = subBuilder.buildPartial();
              }

              break;
            }
            case 48: {

              zoneId_ = input.readInt64();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              locationType_ = rawValue;
              break;
            }
            case 72: {

              parentStation_ = input.readInt64();
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              timezone_ = s;
              break;
            }
            case 88: {
              int rawValue = input.readEnum();

              wheelchairBoarding_ = rawValue;
              break;
            }
            case 96: {

              levelId_ = input.readInt64();
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              platformCode_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StopsProto.internal_static_stops_Stop_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StopsProto.internal_static_stops_Stop_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StopsProto.Stop.class, StopsProto.Stop.Builder.class);
    }

    /**
     * Protobuf enum {@code stops.Stop.LocationType}
     */
    public enum LocationType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PLATFORM = 0;</code>
       */
      PLATFORM(0, 0),
      /**
       * <code>STATION = 1;</code>
       */
      STATION(1, 1),
      /**
       * <code>ENTRANCE = 2;</code>
       */
      ENTRANCE(2, 2),
      /**
       * <code>GENERIC = 3;</code>
       */
      GENERIC(4, 3),
      /**
       * <code>BOARDING = 4;</code>
       */
      BOARDING(5, 4),
      UNRECOGNIZED(-1, -1),
      ;

      /**
       * <code>EXIT = 2;</code>
       */
      public static final LocationType EXIT = ENTRANCE;
      /**
       * <code>PLATFORM = 0;</code>
       */
      public static final int PLATFORM_VALUE = 0;
      /**
       * <code>STATION = 1;</code>
       */
      public static final int STATION_VALUE = 1;
      /**
       * <code>ENTRANCE = 2;</code>
       */
      public static final int ENTRANCE_VALUE = 2;
      /**
       * <code>EXIT = 2;</code>
       */
      public static final int EXIT_VALUE = 2;
      /**
       * <code>GENERIC = 3;</code>
       */
      public static final int GENERIC_VALUE = 3;
      /**
       * <code>BOARDING = 4;</code>
       */
      public static final int BOARDING_VALUE = 4;


      public final int getNumber() {
        if (index == -1) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static LocationType valueOf(int value) {
        return forNumber(value);
      }

      public static LocationType forNumber(int value) {
        switch (value) {
          case 0: return PLATFORM;
          case 1: return STATION;
          case 2: return ENTRANCE;
          case 3: return GENERIC;
          case 4: return BOARDING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<LocationType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          LocationType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<LocationType>() {
              public LocationType findValueByNumber(int number) {
                return LocationType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return StopsProto.Stop.getDescriptor().getEnumTypes().get(0);
      }

      private static final LocationType[] VALUES = {
        PLATFORM, STATION, ENTRANCE, EXIT, GENERIC, BOARDING, 
      };

      public static LocationType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private LocationType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:stops.Stop.LocationType)
    }

    /**
     * Protobuf enum {@code stops.Stop.WheelchairBoarding}
     */
    public enum WheelchairBoarding
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ZERO = 0;</code>
       */
      ZERO(0),
      /**
       * <code>ONE = 1;</code>
       */
      ONE(1),
      /**
       * <code>TWO = 2;</code>
       */
      TWO(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ZERO = 0;</code>
       */
      public static final int ZERO_VALUE = 0;
      /**
       * <code>ONE = 1;</code>
       */
      public static final int ONE_VALUE = 1;
      /**
       * <code>TWO = 2;</code>
       */
      public static final int TWO_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static WheelchairBoarding valueOf(int value) {
        return forNumber(value);
      }

      public static WheelchairBoarding forNumber(int value) {
        switch (value) {
          case 0: return ZERO;
          case 1: return ONE;
          case 2: return TWO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<WheelchairBoarding>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          WheelchairBoarding> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<WheelchairBoarding>() {
              public WheelchairBoarding findValueByNumber(int number) {
                return WheelchairBoarding.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return StopsProto.Stop.getDescriptor().getEnumTypes().get(1);
      }

      private static final WheelchairBoarding[] VALUES = values();

      public static WheelchairBoarding valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private WheelchairBoarding(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:stops.Stop.WheelchairBoarding)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object code_;
    /**
     * <code>string code = 2;</code>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      }
    }
    /**
     * <code>string code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESC_FIELD_NUMBER = 4;
    private volatile java.lang.Object desc_;
    /**
     * <code>string desc = 4;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <code>string desc = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAT_LNG_FIELD_NUMBER = 5;
    private com.google.type.LatLng latLng_;
    /**
     * <code>.google.type.LatLng lat_lng = 5;</code>
     */
    public boolean hasLatLng() {
      return latLng_ != null;
    }
    /**
     * <code>.google.type.LatLng lat_lng = 5;</code>
     */
    public com.google.type.LatLng getLatLng() {
      return latLng_ == null ? com.google.type.LatLng.getDefaultInstance() : latLng_;
    }
    /**
     * <code>.google.type.LatLng lat_lng = 5;</code>
     */
    public com.google.type.LatLngOrBuilder getLatLngOrBuilder() {
      return getLatLng();
    }

    public static final int ZONE_ID_FIELD_NUMBER = 6;
    private long zoneId_;
    /**
     * <code>int64 zone_id = 6;</code>
     */
    public long getZoneId() {
      return zoneId_;
    }

    public static final int URL_FIELD_NUMBER = 7;
    private volatile java.lang.Object url_;
    /**
     * <code>string url = 7;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>string url = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCATION_TYPE_FIELD_NUMBER = 8;
    private int locationType_;
    /**
     * <code>.stops.Stop.LocationType location_type = 8;</code>
     */
    public int getLocationTypeValue() {
      return locationType_;
    }
    /**
     * <code>.stops.Stop.LocationType location_type = 8;</code>
     */
    public StopsProto.Stop.LocationType getLocationType() {
      @SuppressWarnings("deprecation")
      StopsProto.Stop.LocationType result = StopsProto.Stop.LocationType.valueOf(locationType_);
      return result == null ? StopsProto.Stop.LocationType.UNRECOGNIZED : result;
    }

    public static final int PARENT_STATION_FIELD_NUMBER = 9;
    private long parentStation_;
    /**
     * <code>int64 parent_station = 9;</code>
     */
    public long getParentStation() {
      return parentStation_;
    }

    public static final int TIMEZONE_FIELD_NUMBER = 10;
    private volatile java.lang.Object timezone_;
    /**
     * <code>string timezone = 10;</code>
     */
    public java.lang.String getTimezone() {
      java.lang.Object ref = timezone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timezone_ = s;
        return s;
      }
    }
    /**
     * <code>string timezone = 10;</code>
     */
    public com.google.protobuf.ByteString
        getTimezoneBytes() {
      java.lang.Object ref = timezone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timezone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WHEELCHAIR_BOARDING_FIELD_NUMBER = 11;
    private int wheelchairBoarding_;
    /**
     * <code>.stops.Stop.WheelchairBoarding wheelchair_boarding = 11;</code>
     */
    public int getWheelchairBoardingValue() {
      return wheelchairBoarding_;
    }
    /**
     * <code>.stops.Stop.WheelchairBoarding wheelchair_boarding = 11;</code>
     */
    public StopsProto.Stop.WheelchairBoarding getWheelchairBoarding() {
      @SuppressWarnings("deprecation")
      StopsProto.Stop.WheelchairBoarding result = StopsProto.Stop.WheelchairBoarding.valueOf(wheelchairBoarding_);
      return result == null ? StopsProto.Stop.WheelchairBoarding.UNRECOGNIZED : result;
    }

    public static final int LEVEL_ID_FIELD_NUMBER = 12;
    private long levelId_;
    /**
     * <code>int64 level_id = 12;</code>
     */
    public long getLevelId() {
      return levelId_;
    }

    public static final int PLATFORM_CODE_FIELD_NUMBER = 13;
    private volatile java.lang.Object platformCode_;
    /**
     * <code>string platform_code = 13;</code>
     */
    public java.lang.String getPlatformCode() {
      java.lang.Object ref = platformCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platformCode_ = s;
        return s;
      }
    }
    /**
     * <code>string platform_code = 13;</code>
     */
    public com.google.protobuf.ByteString
        getPlatformCodeBytes() {
      java.lang.Object ref = platformCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platformCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!getDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, desc_);
      }
      if (latLng_ != null) {
        output.writeMessage(5, getLatLng());
      }
      if (zoneId_ != 0L) {
        output.writeInt64(6, zoneId_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, url_);
      }
      if (locationType_ != StopsProto.Stop.LocationType.PLATFORM.getNumber()) {
        output.writeEnum(8, locationType_);
      }
      if (parentStation_ != 0L) {
        output.writeInt64(9, parentStation_);
      }
      if (!getTimezoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, timezone_);
      }
      if (wheelchairBoarding_ != StopsProto.Stop.WheelchairBoarding.ZERO.getNumber()) {
        output.writeEnum(11, wheelchairBoarding_);
      }
      if (levelId_ != 0L) {
        output.writeInt64(12, levelId_);
      }
      if (!getPlatformCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, platformCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!getDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, desc_);
      }
      if (latLng_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getLatLng());
      }
      if (zoneId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, zoneId_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, url_);
      }
      if (locationType_ != StopsProto.Stop.LocationType.PLATFORM.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, locationType_);
      }
      if (parentStation_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, parentStation_);
      }
      if (!getTimezoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, timezone_);
      }
      if (wheelchairBoarding_ != StopsProto.Stop.WheelchairBoarding.ZERO.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(11, wheelchairBoarding_);
      }
      if (levelId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, levelId_);
      }
      if (!getPlatformCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, platformCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof StopsProto.Stop)) {
        return super.equals(obj);
      }
      StopsProto.Stop other = (StopsProto.Stop) obj;

      if (getId()
          != other.getId()) return false;
      if (!getCode()
          .equals(other.getCode())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getDesc()
          .equals(other.getDesc())) return false;
      if (hasLatLng() != other.hasLatLng()) return false;
      if (hasLatLng()) {
        if (!getLatLng()
            .equals(other.getLatLng())) return false;
      }
      if (getZoneId()
          != other.getZoneId()) return false;
      if (!getUrl()
          .equals(other.getUrl())) return false;
      if (locationType_ != other.locationType_) return false;
      if (getParentStation()
          != other.getParentStation()) return false;
      if (!getTimezone()
          .equals(other.getTimezone())) return false;
      if (wheelchairBoarding_ != other.wheelchairBoarding_) return false;
      if (getLevelId()
          != other.getLevelId()) return false;
      if (!getPlatformCode()
          .equals(other.getPlatformCode())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      if (hasLatLng()) {
        hash = (37 * hash) + LAT_LNG_FIELD_NUMBER;
        hash = (53 * hash) + getLatLng().hashCode();
      }
      hash = (37 * hash) + ZONE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getZoneId());
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + LOCATION_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + locationType_;
      hash = (37 * hash) + PARENT_STATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getParentStation());
      hash = (37 * hash) + TIMEZONE_FIELD_NUMBER;
      hash = (53 * hash) + getTimezone().hashCode();
      hash = (37 * hash) + WHEELCHAIR_BOARDING_FIELD_NUMBER;
      hash = (53 * hash) + wheelchairBoarding_;
      hash = (37 * hash) + LEVEL_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLevelId());
      hash = (37 * hash) + PLATFORM_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getPlatformCode().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static StopsProto.Stop parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StopsProto.Stop parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StopsProto.Stop parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StopsProto.Stop parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StopsProto.Stop parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StopsProto.Stop parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StopsProto.Stop parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StopsProto.Stop parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static StopsProto.Stop parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static StopsProto.Stop parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static StopsProto.Stop parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StopsProto.Stop parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(StopsProto.Stop prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code stops.Stop}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:stops.Stop)
        StopsProto.StopOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StopsProto.internal_static_stops_Stop_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StopsProto.internal_static_stops_Stop_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StopsProto.Stop.class, StopsProto.Stop.Builder.class);
      }

      // Construct using org.mobilitydata.gtfsproto.StopsProto.Stop.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        code_ = "";

        name_ = "";

        desc_ = "";

        if (latLngBuilder_ == null) {
          latLng_ = null;
        } else {
          latLng_ = null;
          latLngBuilder_ = null;
        }
        zoneId_ = 0L;

        url_ = "";

        locationType_ = 0;

        parentStation_ = 0L;

        timezone_ = "";

        wheelchairBoarding_ = 0;

        levelId_ = 0L;

        platformCode_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StopsProto.internal_static_stops_Stop_descriptor;
      }

      @java.lang.Override
      public StopsProto.Stop getDefaultInstanceForType() {
        return StopsProto.Stop.getDefaultInstance();
      }

      @java.lang.Override
      public StopsProto.Stop build() {
        StopsProto.Stop result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public StopsProto.Stop buildPartial() {
        StopsProto.Stop result = new StopsProto.Stop(this);
        result.id_ = id_;
        result.code_ = code_;
        result.name_ = name_;
        result.desc_ = desc_;
        if (latLngBuilder_ == null) {
          result.latLng_ = latLng_;
        } else {
          result.latLng_ = latLngBuilder_.build();
        }
        result.zoneId_ = zoneId_;
        result.url_ = url_;
        result.locationType_ = locationType_;
        result.parentStation_ = parentStation_;
        result.timezone_ = timezone_;
        result.wheelchairBoarding_ = wheelchairBoarding_;
        result.levelId_ = levelId_;
        result.platformCode_ = platformCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StopsProto.Stop) {
          return mergeFrom((StopsProto.Stop)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(StopsProto.Stop other) {
        if (other == StopsProto.Stop.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getCode().isEmpty()) {
          code_ = other.code_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          onChanged();
        }
        if (other.hasLatLng()) {
          mergeLatLng(other.getLatLng());
        }
        if (other.getZoneId() != 0L) {
          setZoneId(other.getZoneId());
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (other.locationType_ != 0) {
          setLocationTypeValue(other.getLocationTypeValue());
        }
        if (other.getParentStation() != 0L) {
          setParentStation(other.getParentStation());
        }
        if (!other.getTimezone().isEmpty()) {
          timezone_ = other.timezone_;
          onChanged();
        }
        if (other.wheelchairBoarding_ != 0) {
          setWheelchairBoardingValue(other.getWheelchairBoardingValue());
        }
        if (other.getLevelId() != 0L) {
          setLevelId(other.getLevelId());
        }
        if (!other.getPlatformCode().isEmpty()) {
          platformCode_ = other.platformCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        StopsProto.Stop parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (StopsProto.Stop) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object code_ = "";
      /**
       * <code>string code = 2;</code>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string code = 2;</code>
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string code = 2;</code>
       */
      public Builder clearCode() {
        
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <code>string code = 2;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        code_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>string desc = 4;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string desc = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string desc = 4;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 4;</code>
       */
      public Builder clearDesc() {
        
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 4;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        desc_ = value;
        onChanged();
        return this;
      }

      private com.google.type.LatLng latLng_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.type.LatLng, com.google.type.LatLng.Builder, com.google.type.LatLngOrBuilder> latLngBuilder_;
      /**
       * <code>.google.type.LatLng lat_lng = 5;</code>
       */
      public boolean hasLatLng() {
        return latLngBuilder_ != null || latLng_ != null;
      }
      /**
       * <code>.google.type.LatLng lat_lng = 5;</code>
       */
      public com.google.type.LatLng getLatLng() {
        if (latLngBuilder_ == null) {
          return latLng_ == null ? com.google.type.LatLng.getDefaultInstance() : latLng_;
        } else {
          return latLngBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.type.LatLng lat_lng = 5;</code>
       */
      public Builder setLatLng(com.google.type.LatLng value) {
        if (latLngBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          latLng_ = value;
          onChanged();
        } else {
          latLngBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.type.LatLng lat_lng = 5;</code>
       */
      public Builder setLatLng(
          com.google.type.LatLng.Builder builderForValue) {
        if (latLngBuilder_ == null) {
          latLng_ = builderForValue.build();
          onChanged();
        } else {
          latLngBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.type.LatLng lat_lng = 5;</code>
       */
      public Builder mergeLatLng(com.google.type.LatLng value) {
        if (latLngBuilder_ == null) {
          if (latLng_ != null) {
            latLng_ =
              com.google.type.LatLng.newBuilder(latLng_).mergeFrom(value).buildPartial();
          } else {
            latLng_ = value;
          }
          onChanged();
        } else {
          latLngBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.type.LatLng lat_lng = 5;</code>
       */
      public Builder clearLatLng() {
        if (latLngBuilder_ == null) {
          latLng_ = null;
          onChanged();
        } else {
          latLng_ = null;
          latLngBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.type.LatLng lat_lng = 5;</code>
       */
      public com.google.type.LatLng.Builder getLatLngBuilder() {
        
        onChanged();
        return getLatLngFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.type.LatLng lat_lng = 5;</code>
       */
      public com.google.type.LatLngOrBuilder getLatLngOrBuilder() {
        if (latLngBuilder_ != null) {
          return latLngBuilder_.getMessageOrBuilder();
        } else {
          return latLng_ == null ?
              com.google.type.LatLng.getDefaultInstance() : latLng_;
        }
      }
      /**
       * <code>.google.type.LatLng lat_lng = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.type.LatLng, com.google.type.LatLng.Builder, com.google.type.LatLngOrBuilder> 
          getLatLngFieldBuilder() {
        if (latLngBuilder_ == null) {
          latLngBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.type.LatLng, com.google.type.LatLng.Builder, com.google.type.LatLngOrBuilder>(
                  getLatLng(),
                  getParentForChildren(),
                  isClean());
          latLng_ = null;
        }
        return latLngBuilder_;
      }

      private long zoneId_ ;
      /**
       * <code>int64 zone_id = 6;</code>
       */
      public long getZoneId() {
        return zoneId_;
      }
      /**
       * <code>int64 zone_id = 6;</code>
       */
      public Builder setZoneId(long value) {
        
        zoneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 zone_id = 6;</code>
       */
      public Builder clearZoneId() {
        
        zoneId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <code>string url = 7;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string url = 7;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string url = 7;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string url = 7;</code>
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string url = 7;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private int locationType_ = 0;
      /**
       * <code>.stops.Stop.LocationType location_type = 8;</code>
       */
      public int getLocationTypeValue() {
        return locationType_;
      }
      /**
       * <code>.stops.Stop.LocationType location_type = 8;</code>
       */
      public Builder setLocationTypeValue(int value) {
        locationType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.stops.Stop.LocationType location_type = 8;</code>
       */
      public StopsProto.Stop.LocationType getLocationType() {
        @SuppressWarnings("deprecation")
        StopsProto.Stop.LocationType result = StopsProto.Stop.LocationType.valueOf(locationType_);
        return result == null ? StopsProto.Stop.LocationType.UNRECOGNIZED : result;
      }
      /**
       * <code>.stops.Stop.LocationType location_type = 8;</code>
       */
      public Builder setLocationType(StopsProto.Stop.LocationType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        locationType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.stops.Stop.LocationType location_type = 8;</code>
       */
      public Builder clearLocationType() {
        
        locationType_ = 0;
        onChanged();
        return this;
      }

      private long parentStation_ ;
      /**
       * <code>int64 parent_station = 9;</code>
       */
      public long getParentStation() {
        return parentStation_;
      }
      /**
       * <code>int64 parent_station = 9;</code>
       */
      public Builder setParentStation(long value) {
        
        parentStation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 parent_station = 9;</code>
       */
      public Builder clearParentStation() {
        
        parentStation_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object timezone_ = "";
      /**
       * <code>string timezone = 10;</code>
       */
      public java.lang.String getTimezone() {
        java.lang.Object ref = timezone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timezone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string timezone = 10;</code>
       */
      public com.google.protobuf.ByteString
          getTimezoneBytes() {
        java.lang.Object ref = timezone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timezone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string timezone = 10;</code>
       */
      public Builder setTimezone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timezone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string timezone = 10;</code>
       */
      public Builder clearTimezone() {
        
        timezone_ = getDefaultInstance().getTimezone();
        onChanged();
        return this;
      }
      /**
       * <code>string timezone = 10;</code>
       */
      public Builder setTimezoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timezone_ = value;
        onChanged();
        return this;
      }

      private int wheelchairBoarding_ = 0;
      /**
       * <code>.stops.Stop.WheelchairBoarding wheelchair_boarding = 11;</code>
       */
      public int getWheelchairBoardingValue() {
        return wheelchairBoarding_;
      }
      /**
       * <code>.stops.Stop.WheelchairBoarding wheelchair_boarding = 11;</code>
       */
      public Builder setWheelchairBoardingValue(int value) {
        wheelchairBoarding_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.stops.Stop.WheelchairBoarding wheelchair_boarding = 11;</code>
       */
      public StopsProto.Stop.WheelchairBoarding getWheelchairBoarding() {
        @SuppressWarnings("deprecation")
        StopsProto.Stop.WheelchairBoarding result = StopsProto.Stop.WheelchairBoarding.valueOf(wheelchairBoarding_);
        return result == null ? StopsProto.Stop.WheelchairBoarding.UNRECOGNIZED : result;
      }
      /**
       * <code>.stops.Stop.WheelchairBoarding wheelchair_boarding = 11;</code>
       */
      public Builder setWheelchairBoarding(StopsProto.Stop.WheelchairBoarding value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        wheelchairBoarding_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.stops.Stop.WheelchairBoarding wheelchair_boarding = 11;</code>
       */
      public Builder clearWheelchairBoarding() {
        
        wheelchairBoarding_ = 0;
        onChanged();
        return this;
      }

      private long levelId_ ;
      /**
       * <code>int64 level_id = 12;</code>
       */
      public long getLevelId() {
        return levelId_;
      }
      /**
       * <code>int64 level_id = 12;</code>
       */
      public Builder setLevelId(long value) {
        
        levelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 level_id = 12;</code>
       */
      public Builder clearLevelId() {
        
        levelId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object platformCode_ = "";
      /**
       * <code>string platform_code = 13;</code>
       */
      public java.lang.String getPlatformCode() {
        java.lang.Object ref = platformCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          platformCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string platform_code = 13;</code>
       */
      public com.google.protobuf.ByteString
          getPlatformCodeBytes() {
        java.lang.Object ref = platformCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          platformCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string platform_code = 13;</code>
       */
      public Builder setPlatformCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        platformCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string platform_code = 13;</code>
       */
      public Builder clearPlatformCode() {
        
        platformCode_ = getDefaultInstance().getPlatformCode();
        onChanged();
        return this;
      }
      /**
       * <code>string platform_code = 13;</code>
       */
      public Builder setPlatformCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        platformCode_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:stops.Stop)
    }

    // @@protoc_insertion_point(class_scope:stops.Stop)
    private static final StopsProto.Stop DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StopsProto.Stop();
    }

    public static StopsProto.Stop getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Stop>
        PARSER = new com.google.protobuf.AbstractParser<Stop>() {
      @java.lang.Override
      public Stop parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Stop(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Stop> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Stop> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public StopsProto.Stop getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface stopCollectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:stops.stopCollection)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .stops.Stop stops = 1;</code>
     */
    java.util.List<StopsProto.Stop>
        getStopsList();
    /**
     * <code>repeated .stops.Stop stops = 1;</code>
     */
    StopsProto.Stop getStops(int index);
    /**
     * <code>repeated .stops.Stop stops = 1;</code>
     */
    int getStopsCount();
    /**
     * <code>repeated .stops.Stop stops = 1;</code>
     */
    java.util.List<? extends StopsProto.StopOrBuilder>
        getStopsOrBuilderList();
    /**
     * <code>repeated .stops.Stop stops = 1;</code>
     */
    StopsProto.StopOrBuilder getStopsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code stops.stopCollection}
   */
  public  static final class stopCollection extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:stops.stopCollection)
      stopCollectionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use stopCollection.newBuilder() to construct.
    private stopCollection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private stopCollection() {
      stops_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new stopCollection();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private stopCollection(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                stops_ = new java.util.ArrayList<StopsProto.Stop>();
                mutable_bitField0_ |= 0x00000001;
              }
              stops_.add(
                  input.readMessage(StopsProto.Stop.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          stops_ = java.util.Collections.unmodifiableList(stops_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StopsProto.internal_static_stops_stopCollection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StopsProto.internal_static_stops_stopCollection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StopsProto.stopCollection.class, StopsProto.stopCollection.Builder.class);
    }

    public static final int STOPS_FIELD_NUMBER = 1;
    private java.util.List<StopsProto.Stop> stops_;
    /**
     * <code>repeated .stops.Stop stops = 1;</code>
     */
    public java.util.List<StopsProto.Stop> getStopsList() {
      return stops_;
    }
    /**
     * <code>repeated .stops.Stop stops = 1;</code>
     */
    public java.util.List<? extends StopsProto.StopOrBuilder>
        getStopsOrBuilderList() {
      return stops_;
    }
    /**
     * <code>repeated .stops.Stop stops = 1;</code>
     */
    public int getStopsCount() {
      return stops_.size();
    }
    /**
     * <code>repeated .stops.Stop stops = 1;</code>
     */
    public StopsProto.Stop getStops(int index) {
      return stops_.get(index);
    }
    /**
     * <code>repeated .stops.Stop stops = 1;</code>
     */
    public StopsProto.StopOrBuilder getStopsOrBuilder(
        int index) {
      return stops_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < stops_.size(); i++) {
        output.writeMessage(1, stops_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < stops_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, stops_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof StopsProto.stopCollection)) {
        return super.equals(obj);
      }
      StopsProto.stopCollection other = (StopsProto.stopCollection) obj;

      if (!getStopsList()
          .equals(other.getStopsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStopsCount() > 0) {
        hash = (37 * hash) + STOPS_FIELD_NUMBER;
        hash = (53 * hash) + getStopsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static StopsProto.stopCollection parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StopsProto.stopCollection parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StopsProto.stopCollection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StopsProto.stopCollection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StopsProto.stopCollection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StopsProto.stopCollection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StopsProto.stopCollection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StopsProto.stopCollection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static StopsProto.stopCollection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static StopsProto.stopCollection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static StopsProto.stopCollection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StopsProto.stopCollection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(StopsProto.stopCollection prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code stops.stopCollection}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:stops.stopCollection)
        StopsProto.stopCollectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StopsProto.internal_static_stops_stopCollection_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StopsProto.internal_static_stops_stopCollection_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StopsProto.stopCollection.class, StopsProto.stopCollection.Builder.class);
      }

      // Construct using org.mobilitydata.gtfsproto.StopsProto.stopCollection.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStopsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (stopsBuilder_ == null) {
          stops_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          stopsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StopsProto.internal_static_stops_stopCollection_descriptor;
      }

      @java.lang.Override
      public StopsProto.stopCollection getDefaultInstanceForType() {
        return StopsProto.stopCollection.getDefaultInstance();
      }

      @java.lang.Override
      public StopsProto.stopCollection build() {
        StopsProto.stopCollection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public StopsProto.stopCollection buildPartial() {
        StopsProto.stopCollection result = new StopsProto.stopCollection(this);
        int from_bitField0_ = bitField0_;
        if (stopsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            stops_ = java.util.Collections.unmodifiableList(stops_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.stops_ = stops_;
        } else {
          result.stops_ = stopsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StopsProto.stopCollection) {
          return mergeFrom((StopsProto.stopCollection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(StopsProto.stopCollection other) {
        if (other == StopsProto.stopCollection.getDefaultInstance()) return this;
        if (stopsBuilder_ == null) {
          if (!other.stops_.isEmpty()) {
            if (stops_.isEmpty()) {
              stops_ = other.stops_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStopsIsMutable();
              stops_.addAll(other.stops_);
            }
            onChanged();
          }
        } else {
          if (!other.stops_.isEmpty()) {
            if (stopsBuilder_.isEmpty()) {
              stopsBuilder_.dispose();
              stopsBuilder_ = null;
              stops_ = other.stops_;
              bitField0_ = (bitField0_ & ~0x00000001);
              stopsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStopsFieldBuilder() : null;
            } else {
              stopsBuilder_.addAllMessages(other.stops_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        StopsProto.stopCollection parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (StopsProto.stopCollection) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<StopsProto.Stop> stops_ =
        java.util.Collections.emptyList();
      private void ensureStopsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          stops_ = new java.util.ArrayList<StopsProto.Stop>(stops_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          StopsProto.Stop, StopsProto.Stop.Builder, StopsProto.StopOrBuilder> stopsBuilder_;

      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public java.util.List<StopsProto.Stop> getStopsList() {
        if (stopsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(stops_);
        } else {
          return stopsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public int getStopsCount() {
        if (stopsBuilder_ == null) {
          return stops_.size();
        } else {
          return stopsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public StopsProto.Stop getStops(int index) {
        if (stopsBuilder_ == null) {
          return stops_.get(index);
        } else {
          return stopsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public Builder setStops(
          int index, StopsProto.Stop value) {
        if (stopsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStopsIsMutable();
          stops_.set(index, value);
          onChanged();
        } else {
          stopsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public Builder setStops(
          int index, StopsProto.Stop.Builder builderForValue) {
        if (stopsBuilder_ == null) {
          ensureStopsIsMutable();
          stops_.set(index, builderForValue.build());
          onChanged();
        } else {
          stopsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public Builder addStops(StopsProto.Stop value) {
        if (stopsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStopsIsMutable();
          stops_.add(value);
          onChanged();
        } else {
          stopsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public Builder addStops(
          int index, StopsProto.Stop value) {
        if (stopsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStopsIsMutable();
          stops_.add(index, value);
          onChanged();
        } else {
          stopsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public Builder addStops(
          StopsProto.Stop.Builder builderForValue) {
        if (stopsBuilder_ == null) {
          ensureStopsIsMutable();
          stops_.add(builderForValue.build());
          onChanged();
        } else {
          stopsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public Builder addStops(
          int index, StopsProto.Stop.Builder builderForValue) {
        if (stopsBuilder_ == null) {
          ensureStopsIsMutable();
          stops_.add(index, builderForValue.build());
          onChanged();
        } else {
          stopsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public Builder addAllStops(
          java.lang.Iterable<? extends StopsProto.Stop> values) {
        if (stopsBuilder_ == null) {
          ensureStopsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, stops_);
          onChanged();
        } else {
          stopsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public Builder clearStops() {
        if (stopsBuilder_ == null) {
          stops_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          stopsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public Builder removeStops(int index) {
        if (stopsBuilder_ == null) {
          ensureStopsIsMutable();
          stops_.remove(index);
          onChanged();
        } else {
          stopsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public StopsProto.Stop.Builder getStopsBuilder(
          int index) {
        return getStopsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public StopsProto.StopOrBuilder getStopsOrBuilder(
          int index) {
        if (stopsBuilder_ == null) {
          return stops_.get(index);  } else {
          return stopsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public java.util.List<? extends StopsProto.StopOrBuilder>
           getStopsOrBuilderList() {
        if (stopsBuilder_ != null) {
          return stopsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(stops_);
        }
      }
      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public StopsProto.Stop.Builder addStopsBuilder() {
        return getStopsFieldBuilder().addBuilder(
            StopsProto.Stop.getDefaultInstance());
      }
      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public StopsProto.Stop.Builder addStopsBuilder(
          int index) {
        return getStopsFieldBuilder().addBuilder(
            index, StopsProto.Stop.getDefaultInstance());
      }
      /**
       * <code>repeated .stops.Stop stops = 1;</code>
       */
      public java.util.List<StopsProto.Stop.Builder>
           getStopsBuilderList() {
        return getStopsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          StopsProto.Stop, StopsProto.Stop.Builder, StopsProto.StopOrBuilder>
          getStopsFieldBuilder() {
        if (stopsBuilder_ == null) {
          stopsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              StopsProto.Stop, StopsProto.Stop.Builder, StopsProto.StopOrBuilder>(
                  stops_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          stops_ = null;
        }
        return stopsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:stops.stopCollection)
    }

    // @@protoc_insertion_point(class_scope:stops.stopCollection)
    private static final StopsProto.stopCollection DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StopsProto.stopCollection();
    }

    public static StopsProto.stopCollection getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<stopCollection>
        PARSER = new com.google.protobuf.AbstractParser<stopCollection>() {
      @java.lang.Override
      public stopCollection parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new stopCollection(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<stopCollection> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<stopCollection> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public StopsProto.stopCollection getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stops_Stop_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stops_Stop_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stops_stopCollection_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stops_stopCollection_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013stops.proto\022\005stops\032\030google/type/latlng" +
      ".proto\"\325\003\n\004Stop\022\n\n\002id\030\001 \001(\003\022\014\n\004code\030\002 \001(" +
      "\t\022\014\n\004name\030\003 \001(\t\022\014\n\004desc\030\004 \001(\t\022$\n\007lat_lng" +
      "\030\005 \001(\0132\023.google.type.LatLng\022\017\n\007zone_id\030\006" +
      " \001(\003\022\013\n\003url\030\007 \001(\t\022/\n\rlocation_type\030\010 \001(\016" +
      "2\030.stops.Stop.LocationType\022\026\n\016parent_sta" +
      "tion\030\t \001(\003\022\020\n\010timezone\030\n \001(\t\022;\n\023wheelcha" +
      "ir_boarding\030\013 \001(\0162\036.stops.Stop.Wheelchai" +
      "rBoarding\022\020\n\010level_id\030\014 \001(\003\022\025\n\rplatform_" +
      "code\030\r \001(\t\"`\n\014LocationType\022\014\n\010PLATFORM\020\000" +
      "\022\013\n\007STATION\020\001\022\014\n\010ENTRANCE\020\002\022\010\n\004EXIT\020\002\022\013\n" +
      "\007GENERIC\020\003\022\014\n\010BOARDING\020\004\032\002\020\001\"0\n\022Wheelcha" +
      "irBoarding\022\010\n\004ZERO\020\000\022\007\n\003ONE\020\001\022\007\n\003TWO\020\002\"," +
      "\n\016stopCollection\022\032\n\005stops\030\001 \003(\0132\013.stops." +
      "StopB\036\n\020org.mobilitydataB\nStopsProtob\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.type.LatLngProto.getDescriptor(),
        });
    internal_static_stops_Stop_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stops_Stop_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stops_Stop_descriptor,
        new java.lang.String[] { "Id", "Code", "Name", "Desc", "LatLng", "ZoneId", "Url", "LocationType", "ParentStation", "Timezone", "WheelchairBoarding", "LevelId", "PlatformCode", });
    internal_static_stops_stopCollection_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stops_stopCollection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stops_stopCollection_descriptor,
        new java.lang.String[] { "Stops", });
    com.google.type.LatLngProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
