steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/web-based-gtfs-validator/gtfs-validator-web', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/web-based-gtfs-validator/gtfs-validator-web']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'gtfs-validator-web', '--image', 'gcr.io/web-based-gtfs-validator/gtfs-validator-web', '--region', 'us-east1']
images:
  - gcr.io/web-based-gtfs-validator/gtfs-validator-web