#============================================================================================================
# This file contains configuration for https://github.com/zeke/semantic-pull-requests
#============================================================================================================

# Always validate the PR title AND all the commits
titleAndCommits: true
