<script>
  import {marked} from 'marked';
  import {page} from '$app/stores';
  import _ from 'lodash';

  import SectionRefLink from './SectionRefLink.svelte';

  const rules = $page.data.rules || [];
  const summaryMetadata = $page.data.summaryMetadata || [];

  // Group rules by severity level
  $: categories = _.chain(rules)
    .groupBy('severityLevel')
    .toPairs()
    .sortBy(([severityLevel]) => ['ERROR', 'WARNING', 'INFO'].indexOf(severityLevel))
    .fromPairs()
    .value();
  $: deprecatedRules = _.chain(rules)
    .filter(rule => rule.deprecated)
    .groupBy('severityLevel')
    .sortBy(([severityLevel]) => ['ERROR', 'WARNING', 'INFO'].indexOf(severityLevel))
    .flatMap()
    .value();

  /** @param {string} filename */
  function getSpecRef(filename) {
    return `https://gtfs.org/schedule/reference/#${filename.replace('.', '')}`;
  }

  /** @param {string} filename */
  function getBestPracticeRef(filename) {
    return `https://gtfs.org/best-practices/#${filename.replace('.', '')}`;
  }
</script>

<div class="container">
  <div class="flex flex-col md:flex-row md:gap-4 items-baseline">
    <a href="/" class="text-black/50 mr-auto">&larr; Back to validator</a>
    <!-- TODO will there still be a hard copy of this anywhere? -->
    <!-- <a
      href="https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md"
      class="text-black/50"
    >
      View this document on GitHub
    </a> -->
  </div>

  <div class="markdown mt-8 mb-16">
    {#if $page.data.msgHeading}
      <h1 class="h1">{$page.data.msgHeading}</h1>
    {:else}
      <h1 class="h1">Validation Rules and Metadata</h1>
    {/if}

    {#if $page.data.msgBody}
      <p>
        {$page.data.msgBody}
      </p>
    {:else}

      <div class="lg:flex gap-8">
        <div class="order-last">
          <h2 class="h2" id="contents">Contents</h2>

          <ul class="list-disc">
            <li><a href="#introduction">Introduction</a></li>
            <li><a href="#severities">Severities</a></li>
            {#each Object.entries(categories) as [category]}
              <li><a href="#{category}-table">Table of {category} notices</a></li>
            {/each}
            <li><a href="#notice-details">Notice details</a></li>
            <li><a href="#summary-metadata">Summary metadata details</a></li>
          </ul>
        </div>

        <div class="flex-1">
          <h2 class="h2" id="introduction">Introduction</h2>

          <p>This tool is designed to assist you in testing the compliance of a dataset against the GTFS (General
            Transit Feed Specification) Schedule Reference and the GTFS Schedule Best Practices.</p>

          <p>This validator generates a list of notices, each associated with a severity level, allowing you to identify
            and address potential issues in your dataset. This documentation will provide a detailed overview of the
            rules that the validator evaluates, and ways in which the dataset can be fixed if the notice is present.</p>

          <h2 class="h2" id="severities">Severities</h2>

          <p>Each notice generated by the this validator is associated with a severity level: INFO, WARNING, or ERROR.
            Understanding these severities helps in assessing the impact and urgency of addressing the identified
            issues.</p>

          <p><strong>ERROR</strong> notices correspond to GTFS Schedule Reference violations. These violations represent
            items explicitly required or prohibited by the GTFS Schedule Reference, denoted by the use of the terms
            “Required” or “must.” Errors signify critical discrepancies that must be resolved to ensure compliance with
            the GTFS standard.</p>

          <p><strong>WARNING</strong> notices correspond to GTFS Schedule Best Practices. These recommendations are
            either explicitly suggested by the GTFS Schedule Reference, using the term “recommend” or “should,” or
            mentioned in the official GTFS Schedule Best Practices. Although not mandatory, addressing these warnings
            can significantly improve the quality of the data and the rider’s experience.</p>

          <p><strong>INFO</strong> notices highlight items that may affect the overall quality of the feed. These
            notices identify unexpected findings that warrant the user’s attention. </p>
        </div>
      </div>

      {#each Object.entries(categories) as [category, rules]}
        <div id="{category}-table" class="mt-8">
          <h2 class="h2 md:flex items-baseline justify-between">
            <a class="text-base order-last" href="#_top"><i class="fas fa-arrow-up"></i> Top</a>

            <div>
              Table of {category} notices
              <a
                class="text-xl"
                href="#{category}-table"
                title="Link to this section"
              >
                <i class="fa-solid fa-hashtag text-black/30"/>
              </a>
            </div>
          </h2>

          <div class="overflow-x-auto">
            <table class="w-full table-collapse-responsive sm:block lg:table">
              <thead>
              <tr>
                <th>Notice code</th>
                <th>Description</th>
              </tr>
              </thead>
              <tbody>
              {#each rules as rule}
                {#if !rule.deprecated}
                <tr>
                  <td>
                    <a href="#{rule.code}-rule" id="{rule.code}-table">
                      <code class="break-all">{rule.code}</code>
                    </a>
                  </td>
                  <td>
                    <div class="font-bold">{@html marked.parse(rule.shortSummary ?? '')}</div>
                    {@html marked.parse(rule.description ?? '')}
                  </td>
                </tr>
                {/if}
              {/each}
              </tbody>
            </table>
          </div>
        </div>
      {/each}

      <!--{#each Object.entries(categories) as [category, rules]}-->
        <div id="deprecated-rules-table" class="mt-8">
          <h2 class="h2 md:flex items-baseline justify-between">
            <a class="text-base order-last" href="#_top"><i class="fas fa-arrow-up"></i> Top</a>

            <div>
              Table of deprecated notices
              <a
                class="text-xl"
                href="#deprecated-rules-table"
                title="Link to this section"
              >
                <i class="fa-solid fa-hashtag text-black/30"/>
              </a>
            </div>
          </h2>

          <div class="overflow-x-auto">
            <table class="w-full table-collapse-responsive sm:block lg:table">
              <thead>
              <tr>
                <th>Notice code</th>
                <th>Severity</th>
                <th>Deprecated since</th>
                <th>Deprecation reason</th>
              </tr>
              </thead>
              <tbody>
              {#each deprecatedRules as rule}
                  <tr>
                    <td>
                      <a href="#{rule.code}-rule" id="{rule.code}-table">
                        <code class="break-all">{rule.code}</code>
                      </a>
                    </td>
                    <td>{rule.severityLevel}</td>
                    <td>
                      <a href="https://github.com/MobilityData/gtfs-validator/releases/tag/v{rule.deprecationVersion}" target="_blank" rel="noreferrer">
                        {rule.deprecationVersion}
                      </a>
                    </td>
                    <td>
                      {@html marked.parse(rule?.deprecationReason ?? '')}
                    </td>
                  </tr>
              {/each}
              </tbody>
            </table>
          </div>
        </div>
      <!--{/each}-->


      <h2 class="h2" id="notice-details">Notice details</h2>

      {#each Object.entries(rules) as [code, rule]}
        <div id="{rule.code}-rule" class="table-sm">
          <h3 class="h3 md:flex items-baseline justify-between">
            <a class="text-base order-last" href="#{rule.code}-table">
              <i class="fas fa-arrow-up"></i> Table
            </a>

            <div>
              <span class="break-all">{code}</span>
              <span class="text-base deprecated-tag"
                    style="display: {rule.deprecated ? 'inline' : 'none'}">Deprecated</span>
              <a
                class="text-base"
                href="#{rule.code}-rule"
                title="Link to this section"
              >
                <i class="fa-solid fa-hashtag text-black/30"/>
              </a>
            </div>
          </h3>
          <div style="display: {rule.deprecated ? 'inline' : 'none'}">
            This rule is deprecated from the validator since version <b>
            <a
              href="https://github.com/MobilityData/gtfs-validator/releases/tag/v{rule.deprecationVersion}"
              target="_blank" rel="noreferrer"
            >
              {rule.deprecationVersion}
            </a></b>.
            {#if rule.replacementNoticeCodes}
              It has been replaced by
              {#each rule.replacementNoticeCodes as noticeCode, index}
                <code><a href="#{noticeCode}-rule">{noticeCode}</a></code>{index < rule.replacementNoticeCodes.length - 1 ? ', ' : '.'}
              {/each}
            {/if}
            <blockquote>
              <b>Deprecation reason:</b>
              {@html marked.parse(rule?.deprecationReason ?? '')}
            </blockquote>
          </div>

          <blockquote>
            {@html marked.parse(rule.shortSummary ?? '')}
          </blockquote>

          {#if rule.description}
            <div class="overflow-x-auto">
              {@html marked.parse(rule.description)}
            </div>
          {/if}

          {#if rule.references}
            <h4 class="h4">References</h4>
            <ul>
              <!-- TODO: are there any other kinds of references? -->
              {#each rule.references?.sectionReferences ?? [] as ref}
                <li>
                  <SectionRefLink {ref}></SectionRefLink>
                </li>
              {/each}
              {#each rule.references?.fileReferences ?? [] as ref}
                <li>
                  <a href={getSpecRef(ref)} target="_blank" rel="noreferrer">
                    {ref}
                  </a>
                </li>
              {/each}
              {#each rule.references?.bestPracticesFileReferences ?? [] as ref}
                <li>
                  <a
                    href={getBestPracticeRef(ref)}
                    target="_blank"
                    rel="noreferrer"
                  >
                    {ref} Best Practices
                  </a>
                </li>
              {/each}
              {#each rule.references?.urlReferences ?? [] as ref}
                <li>
                  <a href={ref.url} target="_blank" rel="noreferrer">
                    {ref.label}
                  </a>
                </li>
              {/each}
            </ul>
          {/if}

          {#if rule.properties}
            <details>
              <summary>Fields</summary>
              <div class="overflow-x-auto">
                <table class="table-sm">
                  <thead>
                  <tr>
                    <th>Field name</th>
                    <th>Description</th>
                    <th>Type</th>
                  </tr>
                  </thead>
                  <tbody>
                  {#each Object.entries(rule.properties) as [name, property]}
                    <tr>
                      <td><code>{property.fieldName}</code></td>
                      <td>
                        {@html marked.parse(property.shortSummary ?? '')}
                        {@html marked.parse(property.description ?? '\u2014')}
                      </td>
                      <td>{property.type ?? '\u2014'}</td>
                    </tr>
                  {/each}
                  </tbody>
                </table>
              </div>
            </details>
          {/if}
        </div>
      {/each}
    {/if}
  </div>
  <h2 class="h2" id="summary-metadata">Summary metadata details</h2>
  <div>
    This section provides a detailed breakdown of the key elements in the validator’s JSON summary report.
    They capture essential information about your dataset and its compliance with GTFS standards, revealing how related
    fields are structured and interlinked. This section explains the organization and purpose of the elements found in
    the <code>summary</code> section of the report so you can understand the underlying data architecture and how each component
    contributes to the overall summary.
  </div>
  <div class="overflow-x-auto markdown">
    <table class="w-full table-collapse-responsive sm:block lg:table" id="summary-metadata-table">
      <thead>
      <tr>
        <th>Field name</th>
        <th>Type</th>
        <th>Description</th>
      </tr>
      </thead>
      <tbody>
      {#each summaryMetadata as meta}
        <tr>
          <td><code class="break-all" id="summary-{meta.name}">{meta.name}</code></td>
          {#if (meta.fields)}
            <td><a href="#{meta.type.replaceAll('[]', '')}-type"><code>{meta.type}</code></a></td>
          {:else}
            <td>{meta.type}</td>
          {/if}
          <td>{@html marked.parse(meta.description)}</td>
        </tr>
      {/each}
      </tbody>
    </table>
  </div>
  <div class="markdown">
    <h4>Summary metadata custom classes</h4>
    <div class="overflow-x-auto">
      {#each summaryMetadata as meta}
        {#if meta.fields}
          <div id="{meta.type.replaceAll('[]', '')}-type" class="table-sm">
            <h3 class="h3 md:flex items-baseline justify-between">
              <a class="text-base order-last" href="#summary-{meta.name}">
                <i class="fas fa-arrow-up"></i> Table
              </a>
              <div>
                <span class="break-all"><code>{meta.name}</code></span>
                <a
                  class="text-base"
                  href="#{meta.type.replaceAll('[]', '')}-type"
                  title="Link to this section"
                >
                  <i class="fa-solid fa-hashtag text-black/30"/>
                </a>
              </div>
            </h3>
          </div>
          <span>Type of <code>{meta.type}</code></span>
          <blockquote>
            {@html marked.parse(meta.description ?? '')}
          </blockquote>

          <table class="w-full table-collapse-responsive sm:block lg:table">
            <thead>
            <tr>
              <th>Field name</th>
              <th>Type</th>
              <th>Description</th>
            </tr>
            </thead>
            <tbody>
            {#each meta.fields as nested}
              <tr>
                <td><code class="break-all">{nested.name}</code></td>
                <td>{nested.type}</td>
                <td>{@html marked.parse(nested.description)}</td>
              </tr>
            {/each}
            </tbody>
          </table>
        {/if}
      {/each}
    </div>
  </div>

</div>
