package org.mobilitydata.gtfsvalidator.table;

import org.mobilitydata.gtfsvalidator.input.GtfsFeedName;
import org.mobilitydata.gtfsvalidator.notice.NoticeContainer;
import org.mobilitydata.gtfsvalidator.validator.ValidatorLoader;

import java.io.Reader;
import java.util.Set;

/**
 * Loader for a single GTFS table, e.g., stops.txt.
 * <p>
 * Its subclasses are generated by annotation processor based on GTFS schema annotations. The subclasses are annotated
 * with {@code GtfsLoader} to be discovered by {@code GtfsFeedLoader}.
 *
 * @param <T> subclass of {@code GtfsEntity}
 */
public abstract class GtfsTableLoader<T extends GtfsEntity> {
    public abstract String gtfsFilename();

    public abstract Set<String> getColumnNames();

    public abstract Set<String> getRequiredColumnNames();

    public abstract GtfsTableContainer<T> load(Reader reader, GtfsFeedName feedName,
                                               ValidatorLoader validatorLoader, NoticeContainer noticeContainer);

    public abstract GtfsTableContainer<T> loadMissingFile(ValidatorLoader validatorLoader, NoticeContainer noticeContainer);
}
