/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.mobilitydata.gtfsvalidator.table;

import com.google.common.collect.ImmutableList;
import java.util.List;
import java.util.Optional;
import org.mobilitydata.gtfsvalidator.annotation.PrimaryKey;
import org.mobilitydata.gtfsvalidator.parsing.CsvHeader;

/**
 * Container for {@code GtfsEntity} instances coming from a CSV file. e.g., stops.txt.
 *
 * <p>Its subclasses are generated by annotation processor based on GTFS schema annotations.
 *
 * @param <T> subclass of {@code GtfsEntity}
 * @param <D> subclass of {@code GtfsTableDescriptor}
 */
public abstract class GtfsTableContainer<T extends GtfsEntity, D extends GtfsTableDescriptor>
    extends GtfsEntityContainer<T, D> {

  private final CsvHeader header;

  public GtfsTableContainer(D descriptor, TableStatus tableStatus, CsvHeader header) {
    super(descriptor, tableStatus);
    this.header = header;
  }

  public CsvHeader getHeader() {
    return header;
  }

  public abstract Class<T> getEntityClass();

  public int entityCount() {
    return getEntities().size();
  }

  public abstract List<T> getEntities();

  public abstract String gtfsFilename();

  public boolean hasColumn(String columnName) {
    return header.hasColumn(columnName);
  }

  /**
   * Returns names of the columns that are keys in that table.
   *
   * <p>A table may have zero, one, or multiple primary keys, so the returned list contains from 0
   * to N items. Keys are columns annotated with {@link
   * org.mobilitydata.gtfsvalidator.annotation.PrimaryKey}.
   */
  public abstract ImmutableList<String> getKeyColumnNames();

  /**
   * Finds an entity with the given translation record ids.
   *
   * <p>The mapping between translation record ids and primary key columns is table-specific. See
   * {@link PrimaryKey#translationRecordIdType()} for details on configuration. An internal method
   * is generated to construct the proper entity key from the specified String record ids. For
   * single-column primary keys, the <code>recordSubId</code> will be ignored.
   *
   * @param recordId corresponds to translations.txt record_id field.
   * @param recordSubId corresponds translations.txt record_sub_id field.
   * @return entity with the given translation record id, if any
   */
  public abstract Optional<T> byTranslationKey(String recordId, String recordSubId);
}
