/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.mobilitydata.gtfsvalidator.table;

import java.util.List;

/**
 * Container for {@code GtfsEntity} instances for the whole GTFS table, e.g., stops.txt.
 *
 * <p>Its subclasses are generated by annotation processor based on GTFS schema annotations.
 * Instances of the subclasses are created by subclasses of {@code GtfsTableLoader} which are also
 * generated by the processor.
 *
 * @param <T> subclass of {@code GtfsEntity}
 */
public abstract class GtfsTableContainer<T extends GtfsEntity> {

  private final TableStatus tableStatus;

  public GtfsTableContainer(TableStatus tableStatus) {
    this.tableStatus = tableStatus;
  }

  public TableStatus getTableStatus() {
    return tableStatus;
  }

  public abstract Class<T> getEntityClass();

  public int entityCount() {
    return getEntities().size();
  }

  public abstract List<T> getEntities();

  public abstract String gtfsFilename();

  /**
   * Tells if the file is completely empty, i.e. it has no rows and even no headers.
   *
   * @return true if the file is empty, false otherwise
   */
  public boolean isEmptyFile() {
    return tableStatus == TableStatus.EMPTY_FILE;
  }

  /**
   * Tells if the file is missing.
   *
   * @return true if the file is missing, false otherwise
   */
  public boolean isMissingFile() {
    return tableStatus == TableStatus.MISSING_FILE;
  }

  /**
   * Tells if the file is invalid headers, e.g., some required headers are missing.
   *
   * <p>Note that unknown headers are not considered invalid.
   *
   * @return true if the file has invalid headers, false otherwise
   */
  public boolean hasInvalidHeaders() {
    return tableStatus == TableStatus.INVALID_HEADERS;
  }

  /**
   * Tells if some of the rows failed to parse, e.g., have missing required fields or invalid field
   * values.
   *
   * <p>This does not include cross-file or cross-row validation. This also does not include
   * single-entity validation.
   *
   * @return true if some of the rows failed to parse, false otherwise
   */
  public boolean hasUnparsableRows() {
    return tableStatus == TableStatus.UNPARSABLE_ROWS;
  }

  /**
   * Tells if the file is required according to GTFS.
   *
   * <p>Note that a required file may be empty.
   *
   * @return true if the file is required, false otherwise
   */
  public abstract boolean isRequired();

  /**
   * Tells if the file was successfully parsed.
   *
   * <p>If all files in the feed were successfully parsed, then file validators may be executed.
   *
   * <p>A successfully parsed file must meet the following conditions:
   *
   * <ul>
   *   <li>all headers are valid, required headers are present;
   *   <li>all rows are successfully parsed;
   *   <li>if the file is required, it is present in the feed.
   * </ul>
   *
   * @return true if file was successfully parsed, false otherwise
   */
  public boolean isParsedSuccessfully() {
    return !hasInvalidHeaders() && !hasUnparsableRows() && !(isRequired() && isMissingFile());
  }

  public enum TableStatus {
    EMPTY_FILE,
    MISSING_FILE,
    PARSABLE_HEADERS_AND_ROWS,
    INVALID_HEADERS,
    UNPARSABLE_ROWS,
  }
}
