package org.mobilitydata.gtfsvalidator.table;

import java.util.List;

/**
 * Container for {@code GtfsEntity} instances for the whole GTFS table, e.g., stops.txt.
 * <p>
 * Its subclasses are generated by annotation processor based on GTFS schema annotations. Instances of the subclasses
 * are created by subclasses of {@code GtfsTableLoader} which are also generated by the processor.
 *
 * @param <T> subclass of {@code GtfsEntity}
 */
public abstract class GtfsTableContainer<T extends GtfsEntity> {
    private boolean emptyFile = false;
    private boolean missingFile = false;
    private boolean invalidHeaders = false;

    public abstract Class<T> getEntityClass();

    public int entityCount() {
        return getEntities().size();
    }

    public abstract List<T> getEntities();

    public abstract String gtfsFilename();

    public boolean isEmptyFile() {
        return emptyFile;
    }

    public void setEmptyFile(boolean emptyFile) {
        this.emptyFile = emptyFile;
    }

    public boolean isMissingFile() {
        return missingFile;
    }

    public void setMissingFile(boolean missingFile) {
        this.missingFile = missingFile;
    }

    public boolean hasInvalidHeaders() {
        return invalidHeaders;
    }

    public void setInvalidHeaders(boolean invalidHeaders) {
        this.invalidHeaders = invalidHeaders;
    }
}
