name: 'Extract Value'
description: 'Extracts the value for a given key from a GitHub variable'
inputs:
  keys:
    description: 'A list of space separated keys to extract'
    required: true
    type: string
  ONE_PASSWORD_SECRET_REFERENCES:
    description: 'The contents of the ONE_PASSWORD_SECRET_REFERENCES variable'
    required: true
    type: string
  OP_SERVICE_ACCOUNT_TOKEN:
    description: 'The 1Password service account token'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Extract value for specific key
      id: extract_value
      shell: bash
      continue-on-error: true
      env:
        key_values: ${{ inputs.ONE_PASSWORD_SECRET_REFERENCES }}
      run: |
        keys="${{ inputs.keys }}"
        for key in $keys; do
           variable_name=$key
           value=$(echo "$key_values" | grep "^$key *=" | cut -d'=' -f2- | sed 's/^ *//;s/[ \r]*$//')
           echo "key = $key"
           echo "value = $value"
           echo "variable_name = $variable_name"
           export "$variable_name"="$value"
           echo "$variable_name=\"$value\"" >> $GITHUB_ENV
           echo "$variable_name=\"$value\""
        done

    - name: Load secrets from 1Password
      id: onepw_secrets
      uses: 1password/load-secrets-action@v2.0.0
      with:
        export-env: true # Export loaded secrets as environment variables
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ inputs.OP_SERVICE_ACCOUNT_TOKEN }} # This is required to connect to the vault in our 1Password account.
        SONATYPE_TOKEN_USERNAME: $SONATYPE_TOKEN_USERNAME

    - name: print secrets
      shell: bash
      run: |
        echo "The value for the SONATYPE_TOKEN_USERNAME is $SONATYPE_TOKEN_USERNAME"