version: 2.1

jobs:
  pack:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Package cli jar with Gradle
          command: |
            ./gradlew shadowJar
  test:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Run Java tests
          command: |
            ./gradlew testReport
      - run:
          name: Compress Java test report
          command: |
            tar -C build/reports/allTests/ -cvf java-tests-v1.3.0-SNAPSHOT.tar .

workflows:
  version: 2
  test_pack_doc:
    jobs:
      - test
      - pack:
          requires:
            - test
