version: 2.1

jobs:
  package:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Package with Gradle
          command: |
            ./gradlew shadowJar
      - store_artifacts:
          path: application/cli-app/build/libs/gtfs-validator-v1.3.0-SNAPSHOT.jar

workflows:
  version: 2
  build_and_test:
    jobs:
      - package
