# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  gradle: circleci/gradle@2.2.0

jobs:
  package:
    docker:
      - image: circleci/openjdk:11
    steps:
      - gradle/run:
          name: Package with Gradle
          command: shadowJar
 

workflows:
  version: 2
  build_and_test:
    jobs:
      - package
