version: 2.1

jobs:
  package:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Package cli jar with Gradle
          command: |
            ./gradlew shadowJar
      - store_artifacts:
          path: application/cli-app/build/libs/gtfs-validator-v1.3.0-SNAPSHOT_cli.jar
          destination: gtfs-validator-v1.3.0-SNAPSHOT_cli.jar
  test:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Run Java tests
          command: |
            ./gradlew testReport
      - run:
          name: Compress Java test report
          command: |
            tar -C build/reports/allTests/ -cvf v1.3.0-SNAPSHOT_tests_java.tar .
      - store_artifacts:
          path: v1.3.0-SNAPSHOT_tests_java.tar
          destination: v1.3.0-SNAPSHOT_tests_java.tar
  doc:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Generate javadoc
          command: |
            ./gradlew aggregateJavadocs
      - run:
          name: Compress javadoc
          command: |
            tar -C build/docs/javadoc/ -cvf v1.3.0-SNAPSHOT_javadoc.tar .
      - store_artifacts:
          path: v1.3.0-SNAPSHOT_javadoc.tar
          destination: v1.3.0-SNAPSHOT_javadoc.tar

workflows:
  version: 2
  package_test_document:
    jobs:
      - test
      - package:
          requires:
            - test
      - doc:
          requires:
            - test
