# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
orbs:
  gradle: circleci/gradle@2.2.0
version: 2.1
workflows:
  test-package-document:
    jobs:
      - gradle/run:
          command: testReport
      - gradle/run:
          command: shadowJar
      - gradle/run:
          command: aggregateJavadocs
      - collect_test_results:
          path: application/cli-app/build/libs/gtfs-validator-v1.3.0-SNAPSHOT.jar
