# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
orbs:
  gradle: circleci/gradle@2.2.0
version: 2.1
workflows:
  checkout-build-test:
    jobs:
      - gradle/run:
          command: testReport
