// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stop_times.proto

package org.mobilitydata.gtfsvalidator.proto;

/*
 * Copyright (c) 2019. MobilityData IO. All rights reserved
 */

public final class StopTimesProto {
  private StopTimesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StopTimeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:stoptimes.StopTime)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string trip_id = 1;</code>
     */
    java.lang.String getTripId();
    /**
     * <code>string trip_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getTripIdBytes();

    /**
     * <code>string arrival_time = 2;</code>
     */
    java.lang.String getArrivalTime();
    /**
     * <code>string arrival_time = 2;</code>
     */
    com.google.protobuf.ByteString
        getArrivalTimeBytes();

    /**
     * <code>string departure_time = 3;</code>
     */
    java.lang.String getDepartureTime();
    /**
     * <code>string departure_time = 3;</code>
     */
    com.google.protobuf.ByteString
        getDepartureTimeBytes();

    /**
     * <code>string stop_id = 4;</code>
     */
    java.lang.String getStopId();
    /**
     * <code>string stop_id = 4;</code>
     */
    com.google.protobuf.ByteString
        getStopIdBytes();

    /**
     * <code>uint32 stop_sequence = 5;</code>
     */
    int getStopSequence();

    /**
     * <code>string stop_headsign = 6;</code>
     */
    java.lang.String getStopHeadsign();
    /**
     * <code>string stop_headsign = 6;</code>
     */
    com.google.protobuf.ByteString
        getStopHeadsignBytes();

    /**
     * <code>.stoptimes.StopTime.PickupDropOffType pickup_type = 7;</code>
     */
    int getPickupTypeValue();
    /**
     * <code>.stoptimes.StopTime.PickupDropOffType pickup_type = 7;</code>
     */
    StopTimesProto.StopTime.PickupDropOffType getPickupType();

    /**
     * <code>.stoptimes.StopTime.PickupDropOffType drop_off_type = 8;</code>
     */
    int getDropOffTypeValue();
    /**
     * <code>.stoptimes.StopTime.PickupDropOffType drop_off_type = 8;</code>
     */
    StopTimesProto.StopTime.PickupDropOffType getDropOffType();

    /**
     * <code>float shape_dist_traveled = 9;</code>
     */
    float getShapeDistTraveled();

    /**
     * <code>.stoptimes.StopTime.TimePrecision timepoint = 10;</code>
     */
    int getTimepointValue();
    /**
     * <code>.stoptimes.StopTime.TimePrecision timepoint = 10;</code>
     */
    StopTimesProto.StopTime.TimePrecision getTimepoint();
  }
  /**
   * Protobuf type {@code stoptimes.StopTime}
   */
  public  static final class StopTime extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:stoptimes.StopTime)
      StopTimeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StopTime.newBuilder() to construct.
    private StopTime(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StopTime() {
      tripId_ = "";
      arrivalTime_ = "";
      departureTime_ = "";
      stopId_ = "";
      stopHeadsign_ = "";
      pickupType_ = 0;
      dropOffType_ = 0;
      timepoint_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StopTime();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StopTime(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              tripId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              arrivalTime_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              departureTime_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              stopId_ = s;
              break;
            }
            case 40: {

              stopSequence_ = input.readUInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              stopHeadsign_ = s;
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              pickupType_ = rawValue;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              dropOffType_ = rawValue;
              break;
            }
            case 77: {

              shapeDistTraveled_ = input.readFloat();
              break;
            }
            case 80: {
              int rawValue = input.readEnum();

              timepoint_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StopTimesProto.internal_static_stoptimes_StopTime_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StopTimesProto.internal_static_stoptimes_StopTime_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StopTimesProto.StopTime.class, StopTimesProto.StopTime.Builder.class);
    }

    /**
     * Protobuf enum {@code stoptimes.StopTime.PickupDropOffType}
     */
    public enum PickupDropOffType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REGULAR = 0;</code>
       */
      REGULAR(0),
      /**
       * <code>NONE = 1;</code>
       */
      NONE(1),
      /**
       * <code>AGENCY = 2;</code>
       */
      AGENCY(2),
      /**
       * <code>DRIVER = 3;</code>
       */
      DRIVER(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>REGULAR = 0;</code>
       */
      public static final int REGULAR_VALUE = 0;
      /**
       * <code>NONE = 1;</code>
       */
      public static final int NONE_VALUE = 1;
      /**
       * <code>AGENCY = 2;</code>
       */
      public static final int AGENCY_VALUE = 2;
      /**
       * <code>DRIVER = 3;</code>
       */
      public static final int DRIVER_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PickupDropOffType valueOf(int value) {
        return forNumber(value);
      }

      public static PickupDropOffType forNumber(int value) {
        switch (value) {
          case 0: return REGULAR;
          case 1: return NONE;
          case 2: return AGENCY;
          case 3: return DRIVER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PickupDropOffType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PickupDropOffType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PickupDropOffType>() {
              public PickupDropOffType findValueByNumber(int number) {
                return PickupDropOffType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return StopTimesProto.StopTime.getDescriptor().getEnumTypes().get(0);
      }

      private static final PickupDropOffType[] VALUES = values();

      public static PickupDropOffType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PickupDropOffType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:stoptimes.StopTime.PickupDropOffType)
    }

    /**
     * Protobuf enum {@code stoptimes.StopTime.TimePrecision}
     */
    public enum TimePrecision
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>APPROXIMATE = 0;</code>
       */
      APPROXIMATE(0),
      /**
       * <code>EXACT = 1;</code>
       */
      EXACT(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>APPROXIMATE = 0;</code>
       */
      public static final int APPROXIMATE_VALUE = 0;
      /**
       * <code>EXACT = 1;</code>
       */
      public static final int EXACT_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TimePrecision valueOf(int value) {
        return forNumber(value);
      }

      public static TimePrecision forNumber(int value) {
        switch (value) {
          case 0: return APPROXIMATE;
          case 1: return EXACT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TimePrecision>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          TimePrecision> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TimePrecision>() {
              public TimePrecision findValueByNumber(int number) {
                return TimePrecision.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return StopTimesProto.StopTime.getDescriptor().getEnumTypes().get(1);
      }

      private static final TimePrecision[] VALUES = values();

      public static TimePrecision valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private TimePrecision(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:stoptimes.StopTime.TimePrecision)
    }

    public static final int TRIP_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object tripId_;
    /**
     * <code>string trip_id = 1;</code>
     */
    public java.lang.String getTripId() {
      java.lang.Object ref = tripId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tripId_ = s;
        return s;
      }
    }
    /**
     * <code>string trip_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTripIdBytes() {
      java.lang.Object ref = tripId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tripId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARRIVAL_TIME_FIELD_NUMBER = 2;
    private volatile java.lang.Object arrivalTime_;
    /**
     * <code>string arrival_time = 2;</code>
     */
    public java.lang.String getArrivalTime() {
      java.lang.Object ref = arrivalTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        arrivalTime_ = s;
        return s;
      }
    }
    /**
     * <code>string arrival_time = 2;</code>
     */
    public com.google.protobuf.ByteString
        getArrivalTimeBytes() {
      java.lang.Object ref = arrivalTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arrivalTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEPARTURE_TIME_FIELD_NUMBER = 3;
    private volatile java.lang.Object departureTime_;
    /**
     * <code>string departure_time = 3;</code>
     */
    public java.lang.String getDepartureTime() {
      java.lang.Object ref = departureTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        departureTime_ = s;
        return s;
      }
    }
    /**
     * <code>string departure_time = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDepartureTimeBytes() {
      java.lang.Object ref = departureTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        departureTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STOP_ID_FIELD_NUMBER = 4;
    private volatile java.lang.Object stopId_;
    /**
     * <code>string stop_id = 4;</code>
     */
    public java.lang.String getStopId() {
      java.lang.Object ref = stopId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stopId_ = s;
        return s;
      }
    }
    /**
     * <code>string stop_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStopIdBytes() {
      java.lang.Object ref = stopId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stopId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STOP_SEQUENCE_FIELD_NUMBER = 5;
    private int stopSequence_;
    /**
     * <code>uint32 stop_sequence = 5;</code>
     */
    public int getStopSequence() {
      return stopSequence_;
    }

    public static final int STOP_HEADSIGN_FIELD_NUMBER = 6;
    private volatile java.lang.Object stopHeadsign_;
    /**
     * <code>string stop_headsign = 6;</code>
     */
    public java.lang.String getStopHeadsign() {
      java.lang.Object ref = stopHeadsign_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stopHeadsign_ = s;
        return s;
      }
    }
    /**
     * <code>string stop_headsign = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStopHeadsignBytes() {
      java.lang.Object ref = stopHeadsign_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stopHeadsign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PICKUP_TYPE_FIELD_NUMBER = 7;
    private int pickupType_;
    /**
     * <code>.stoptimes.StopTime.PickupDropOffType pickup_type = 7;</code>
     */
    public int getPickupTypeValue() {
      return pickupType_;
    }
    /**
     * <code>.stoptimes.StopTime.PickupDropOffType pickup_type = 7;</code>
     */
    public StopTimesProto.StopTime.PickupDropOffType getPickupType() {
      @SuppressWarnings("deprecation")
      StopTimesProto.StopTime.PickupDropOffType result = StopTimesProto.StopTime.PickupDropOffType.valueOf(pickupType_);
      return result == null ? StopTimesProto.StopTime.PickupDropOffType.UNRECOGNIZED : result;
    }

    public static final int DROP_OFF_TYPE_FIELD_NUMBER = 8;
    private int dropOffType_;
    /**
     * <code>.stoptimes.StopTime.PickupDropOffType drop_off_type = 8;</code>
     */
    public int getDropOffTypeValue() {
      return dropOffType_;
    }
    /**
     * <code>.stoptimes.StopTime.PickupDropOffType drop_off_type = 8;</code>
     */
    public StopTimesProto.StopTime.PickupDropOffType getDropOffType() {
      @SuppressWarnings("deprecation")
      StopTimesProto.StopTime.PickupDropOffType result = StopTimesProto.StopTime.PickupDropOffType.valueOf(dropOffType_);
      return result == null ? StopTimesProto.StopTime.PickupDropOffType.UNRECOGNIZED : result;
    }

    public static final int SHAPE_DIST_TRAVELED_FIELD_NUMBER = 9;
    private float shapeDistTraveled_;
    /**
     * <code>float shape_dist_traveled = 9;</code>
     */
    public float getShapeDistTraveled() {
      return shapeDistTraveled_;
    }

    public static final int TIMEPOINT_FIELD_NUMBER = 10;
    private int timepoint_;
    /**
     * <code>.stoptimes.StopTime.TimePrecision timepoint = 10;</code>
     */
    public int getTimepointValue() {
      return timepoint_;
    }
    /**
     * <code>.stoptimes.StopTime.TimePrecision timepoint = 10;</code>
     */
    public StopTimesProto.StopTime.TimePrecision getTimepoint() {
      @SuppressWarnings("deprecation")
      StopTimesProto.StopTime.TimePrecision result = StopTimesProto.StopTime.TimePrecision.valueOf(timepoint_);
      return result == null ? StopTimesProto.StopTime.TimePrecision.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTripIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tripId_);
      }
      if (!getArrivalTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, arrivalTime_);
      }
      if (!getDepartureTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, departureTime_);
      }
      if (!getStopIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, stopId_);
      }
      if (stopSequence_ != 0) {
        output.writeUInt32(5, stopSequence_);
      }
      if (!getStopHeadsignBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, stopHeadsign_);
      }
      if (pickupType_ != StopTimesProto.StopTime.PickupDropOffType.REGULAR.getNumber()) {
        output.writeEnum(7, pickupType_);
      }
      if (dropOffType_ != StopTimesProto.StopTime.PickupDropOffType.REGULAR.getNumber()) {
        output.writeEnum(8, dropOffType_);
      }
      if (shapeDistTraveled_ != 0F) {
        output.writeFloat(9, shapeDistTraveled_);
      }
      if (timepoint_ != StopTimesProto.StopTime.TimePrecision.APPROXIMATE.getNumber()) {
        output.writeEnum(10, timepoint_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTripIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tripId_);
      }
      if (!getArrivalTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, arrivalTime_);
      }
      if (!getDepartureTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, departureTime_);
      }
      if (!getStopIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, stopId_);
      }
      if (stopSequence_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, stopSequence_);
      }
      if (!getStopHeadsignBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, stopHeadsign_);
      }
      if (pickupType_ != StopTimesProto.StopTime.PickupDropOffType.REGULAR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, pickupType_);
      }
      if (dropOffType_ != StopTimesProto.StopTime.PickupDropOffType.REGULAR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, dropOffType_);
      }
      if (shapeDistTraveled_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, shapeDistTraveled_);
      }
      if (timepoint_ != StopTimesProto.StopTime.TimePrecision.APPROXIMATE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, timepoint_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof StopTimesProto.StopTime)) {
        return super.equals(obj);
      }
      StopTimesProto.StopTime other = (StopTimesProto.StopTime) obj;

      if (!getTripId()
          .equals(other.getTripId())) return false;
      if (!getArrivalTime()
          .equals(other.getArrivalTime())) return false;
      if (!getDepartureTime()
          .equals(other.getDepartureTime())) return false;
      if (!getStopId()
          .equals(other.getStopId())) return false;
      if (getStopSequence()
          != other.getStopSequence()) return false;
      if (!getStopHeadsign()
          .equals(other.getStopHeadsign())) return false;
      if (pickupType_ != other.pickupType_) return false;
      if (dropOffType_ != other.dropOffType_) return false;
      if (java.lang.Float.floatToIntBits(getShapeDistTraveled())
          != java.lang.Float.floatToIntBits(
              other.getShapeDistTraveled())) return false;
      if (timepoint_ != other.timepoint_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TRIP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTripId().hashCode();
      hash = (37 * hash) + ARRIVAL_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getArrivalTime().hashCode();
      hash = (37 * hash) + DEPARTURE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getDepartureTime().hashCode();
      hash = (37 * hash) + STOP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getStopId().hashCode();
      hash = (37 * hash) + STOP_SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + getStopSequence();
      hash = (37 * hash) + STOP_HEADSIGN_FIELD_NUMBER;
      hash = (53 * hash) + getStopHeadsign().hashCode();
      hash = (37 * hash) + PICKUP_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + pickupType_;
      hash = (37 * hash) + DROP_OFF_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dropOffType_;
      hash = (37 * hash) + SHAPE_DIST_TRAVELED_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getShapeDistTraveled());
      hash = (37 * hash) + TIMEPOINT_FIELD_NUMBER;
      hash = (53 * hash) + timepoint_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static StopTimesProto.StopTime parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StopTimesProto.StopTime parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StopTimesProto.StopTime parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StopTimesProto.StopTime parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StopTimesProto.StopTime parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StopTimesProto.StopTime parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StopTimesProto.StopTime parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StopTimesProto.StopTime parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static StopTimesProto.StopTime parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static StopTimesProto.StopTime parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static StopTimesProto.StopTime parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StopTimesProto.StopTime parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(StopTimesProto.StopTime prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code stoptimes.StopTime}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:stoptimes.StopTime)
        StopTimesProto.StopTimeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StopTimesProto.internal_static_stoptimes_StopTime_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StopTimesProto.internal_static_stoptimes_StopTime_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StopTimesProto.StopTime.class, StopTimesProto.StopTime.Builder.class);
      }

      // Construct using org.mobilitydata.gtfsproto.StopTimesProto.StopTime.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        tripId_ = "";

        arrivalTime_ = "";

        departureTime_ = "";

        stopId_ = "";

        stopSequence_ = 0;

        stopHeadsign_ = "";

        pickupType_ = 0;

        dropOffType_ = 0;

        shapeDistTraveled_ = 0F;

        timepoint_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StopTimesProto.internal_static_stoptimes_StopTime_descriptor;
      }

      @java.lang.Override
      public StopTimesProto.StopTime getDefaultInstanceForType() {
        return StopTimesProto.StopTime.getDefaultInstance();
      }

      @java.lang.Override
      public StopTimesProto.StopTime build() {
        StopTimesProto.StopTime result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public StopTimesProto.StopTime buildPartial() {
        StopTimesProto.StopTime result = new StopTimesProto.StopTime(this);
        result.tripId_ = tripId_;
        result.arrivalTime_ = arrivalTime_;
        result.departureTime_ = departureTime_;
        result.stopId_ = stopId_;
        result.stopSequence_ = stopSequence_;
        result.stopHeadsign_ = stopHeadsign_;
        result.pickupType_ = pickupType_;
        result.dropOffType_ = dropOffType_;
        result.shapeDistTraveled_ = shapeDistTraveled_;
        result.timepoint_ = timepoint_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StopTimesProto.StopTime) {
          return mergeFrom((StopTimesProto.StopTime)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(StopTimesProto.StopTime other) {
        if (other == StopTimesProto.StopTime.getDefaultInstance()) return this;
        if (!other.getTripId().isEmpty()) {
          tripId_ = other.tripId_;
          onChanged();
        }
        if (!other.getArrivalTime().isEmpty()) {
          arrivalTime_ = other.arrivalTime_;
          onChanged();
        }
        if (!other.getDepartureTime().isEmpty()) {
          departureTime_ = other.departureTime_;
          onChanged();
        }
        if (!other.getStopId().isEmpty()) {
          stopId_ = other.stopId_;
          onChanged();
        }
        if (other.getStopSequence() != 0) {
          setStopSequence(other.getStopSequence());
        }
        if (!other.getStopHeadsign().isEmpty()) {
          stopHeadsign_ = other.stopHeadsign_;
          onChanged();
        }
        if (other.pickupType_ != 0) {
          setPickupTypeValue(other.getPickupTypeValue());
        }
        if (other.dropOffType_ != 0) {
          setDropOffTypeValue(other.getDropOffTypeValue());
        }
        if (other.getShapeDistTraveled() != 0F) {
          setShapeDistTraveled(other.getShapeDistTraveled());
        }
        if (other.timepoint_ != 0) {
          setTimepointValue(other.getTimepointValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        StopTimesProto.StopTime parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (StopTimesProto.StopTime) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object tripId_ = "";
      /**
       * <code>string trip_id = 1;</code>
       */
      public java.lang.String getTripId() {
        java.lang.Object ref = tripId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tripId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string trip_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTripIdBytes() {
        java.lang.Object ref = tripId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tripId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string trip_id = 1;</code>
       */
      public Builder setTripId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tripId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string trip_id = 1;</code>
       */
      public Builder clearTripId() {
        
        tripId_ = getDefaultInstance().getTripId();
        onChanged();
        return this;
      }
      /**
       * <code>string trip_id = 1;</code>
       */
      public Builder setTripIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tripId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object arrivalTime_ = "";
      /**
       * <code>string arrival_time = 2;</code>
       */
      public java.lang.String getArrivalTime() {
        java.lang.Object ref = arrivalTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          arrivalTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string arrival_time = 2;</code>
       */
      public com.google.protobuf.ByteString
          getArrivalTimeBytes() {
        java.lang.Object ref = arrivalTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          arrivalTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string arrival_time = 2;</code>
       */
      public Builder setArrivalTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        arrivalTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string arrival_time = 2;</code>
       */
      public Builder clearArrivalTime() {
        
        arrivalTime_ = getDefaultInstance().getArrivalTime();
        onChanged();
        return this;
      }
      /**
       * <code>string arrival_time = 2;</code>
       */
      public Builder setArrivalTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        arrivalTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object departureTime_ = "";
      /**
       * <code>string departure_time = 3;</code>
       */
      public java.lang.String getDepartureTime() {
        java.lang.Object ref = departureTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          departureTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string departure_time = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDepartureTimeBytes() {
        java.lang.Object ref = departureTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          departureTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string departure_time = 3;</code>
       */
      public Builder setDepartureTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        departureTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string departure_time = 3;</code>
       */
      public Builder clearDepartureTime() {
        
        departureTime_ = getDefaultInstance().getDepartureTime();
        onChanged();
        return this;
      }
      /**
       * <code>string departure_time = 3;</code>
       */
      public Builder setDepartureTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        departureTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object stopId_ = "";
      /**
       * <code>string stop_id = 4;</code>
       */
      public java.lang.String getStopId() {
        java.lang.Object ref = stopId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stopId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stop_id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStopIdBytes() {
        java.lang.Object ref = stopId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stopId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stop_id = 4;</code>
       */
      public Builder setStopId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stopId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stop_id = 4;</code>
       */
      public Builder clearStopId() {
        
        stopId_ = getDefaultInstance().getStopId();
        onChanged();
        return this;
      }
      /**
       * <code>string stop_id = 4;</code>
       */
      public Builder setStopIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stopId_ = value;
        onChanged();
        return this;
      }

      private int stopSequence_ ;
      /**
       * <code>uint32 stop_sequence = 5;</code>
       */
      public int getStopSequence() {
        return stopSequence_;
      }
      /**
       * <code>uint32 stop_sequence = 5;</code>
       */
      public Builder setStopSequence(int value) {
        
        stopSequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 stop_sequence = 5;</code>
       */
      public Builder clearStopSequence() {
        
        stopSequence_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object stopHeadsign_ = "";
      /**
       * <code>string stop_headsign = 6;</code>
       */
      public java.lang.String getStopHeadsign() {
        java.lang.Object ref = stopHeadsign_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stopHeadsign_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stop_headsign = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStopHeadsignBytes() {
        java.lang.Object ref = stopHeadsign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stopHeadsign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stop_headsign = 6;</code>
       */
      public Builder setStopHeadsign(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stopHeadsign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stop_headsign = 6;</code>
       */
      public Builder clearStopHeadsign() {
        
        stopHeadsign_ = getDefaultInstance().getStopHeadsign();
        onChanged();
        return this;
      }
      /**
       * <code>string stop_headsign = 6;</code>
       */
      public Builder setStopHeadsignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stopHeadsign_ = value;
        onChanged();
        return this;
      }

      private int pickupType_ = 0;
      /**
       * <code>.stoptimes.StopTime.PickupDropOffType pickup_type = 7;</code>
       */
      public int getPickupTypeValue() {
        return pickupType_;
      }
      /**
       * <code>.stoptimes.StopTime.PickupDropOffType pickup_type = 7;</code>
       */
      public Builder setPickupTypeValue(int value) {
        pickupType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.stoptimes.StopTime.PickupDropOffType pickup_type = 7;</code>
       */
      public StopTimesProto.StopTime.PickupDropOffType getPickupType() {
        @SuppressWarnings("deprecation")
        StopTimesProto.StopTime.PickupDropOffType result = StopTimesProto.StopTime.PickupDropOffType.valueOf(pickupType_);
        return result == null ? StopTimesProto.StopTime.PickupDropOffType.UNRECOGNIZED : result;
      }
      /**
       * <code>.stoptimes.StopTime.PickupDropOffType pickup_type = 7;</code>
       */
      public Builder setPickupType(StopTimesProto.StopTime.PickupDropOffType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        pickupType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.stoptimes.StopTime.PickupDropOffType pickup_type = 7;</code>
       */
      public Builder clearPickupType() {
        
        pickupType_ = 0;
        onChanged();
        return this;
      }

      private int dropOffType_ = 0;
      /**
       * <code>.stoptimes.StopTime.PickupDropOffType drop_off_type = 8;</code>
       */
      public int getDropOffTypeValue() {
        return dropOffType_;
      }
      /**
       * <code>.stoptimes.StopTime.PickupDropOffType drop_off_type = 8;</code>
       */
      public Builder setDropOffTypeValue(int value) {
        dropOffType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.stoptimes.StopTime.PickupDropOffType drop_off_type = 8;</code>
       */
      public StopTimesProto.StopTime.PickupDropOffType getDropOffType() {
        @SuppressWarnings("deprecation")
        StopTimesProto.StopTime.PickupDropOffType result = StopTimesProto.StopTime.PickupDropOffType.valueOf(dropOffType_);
        return result == null ? StopTimesProto.StopTime.PickupDropOffType.UNRECOGNIZED : result;
      }
      /**
       * <code>.stoptimes.StopTime.PickupDropOffType drop_off_type = 8;</code>
       */
      public Builder setDropOffType(StopTimesProto.StopTime.PickupDropOffType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dropOffType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.stoptimes.StopTime.PickupDropOffType drop_off_type = 8;</code>
       */
      public Builder clearDropOffType() {
        
        dropOffType_ = 0;
        onChanged();
        return this;
      }

      private float shapeDistTraveled_ ;
      /**
       * <code>float shape_dist_traveled = 9;</code>
       */
      public float getShapeDistTraveled() {
        return shapeDistTraveled_;
      }
      /**
       * <code>float shape_dist_traveled = 9;</code>
       */
      public Builder setShapeDistTraveled(float value) {
        
        shapeDistTraveled_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float shape_dist_traveled = 9;</code>
       */
      public Builder clearShapeDistTraveled() {
        
        shapeDistTraveled_ = 0F;
        onChanged();
        return this;
      }

      private int timepoint_ = 0;
      /**
       * <code>.stoptimes.StopTime.TimePrecision timepoint = 10;</code>
       */
      public int getTimepointValue() {
        return timepoint_;
      }
      /**
       * <code>.stoptimes.StopTime.TimePrecision timepoint = 10;</code>
       */
      public Builder setTimepointValue(int value) {
        timepoint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.stoptimes.StopTime.TimePrecision timepoint = 10;</code>
       */
      public StopTimesProto.StopTime.TimePrecision getTimepoint() {
        @SuppressWarnings("deprecation")
        StopTimesProto.StopTime.TimePrecision result = StopTimesProto.StopTime.TimePrecision.valueOf(timepoint_);
        return result == null ? StopTimesProto.StopTime.TimePrecision.UNRECOGNIZED : result;
      }
      /**
       * <code>.stoptimes.StopTime.TimePrecision timepoint = 10;</code>
       */
      public Builder setTimepoint(StopTimesProto.StopTime.TimePrecision value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        timepoint_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.stoptimes.StopTime.TimePrecision timepoint = 10;</code>
       */
      public Builder clearTimepoint() {
        
        timepoint_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:stoptimes.StopTime)
    }

    // @@protoc_insertion_point(class_scope:stoptimes.StopTime)
    private static final StopTimesProto.StopTime DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StopTimesProto.StopTime();
    }

    public static StopTimesProto.StopTime getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StopTime>
        PARSER = new com.google.protobuf.AbstractParser<StopTime>() {
      @java.lang.Override
      public StopTime parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StopTime(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StopTime> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StopTime> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public StopTimesProto.StopTime getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface stopTimeCollectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:stoptimes.stopTimeCollection)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
     */
    java.util.List<StopTimesProto.StopTime>
        getStopTimesList();
    /**
     * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
     */
    StopTimesProto.StopTime getStopTimes(int index);
    /**
     * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
     */
    int getStopTimesCount();
    /**
     * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
     */
    java.util.List<? extends StopTimesProto.StopTimeOrBuilder>
        getStopTimesOrBuilderList();
    /**
     * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
     */
    StopTimesProto.StopTimeOrBuilder getStopTimesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code stoptimes.stopTimeCollection}
   */
  public  static final class stopTimeCollection extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:stoptimes.stopTimeCollection)
      stopTimeCollectionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use stopTimeCollection.newBuilder() to construct.
    private stopTimeCollection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private stopTimeCollection() {
      stopTimes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new stopTimeCollection();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private stopTimeCollection(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                stopTimes_ = new java.util.ArrayList<StopTimesProto.StopTime>();
                mutable_bitField0_ |= 0x00000001;
              }
              stopTimes_.add(
                  input.readMessage(StopTimesProto.StopTime.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          stopTimes_ = java.util.Collections.unmodifiableList(stopTimes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StopTimesProto.internal_static_stoptimes_stopTimeCollection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StopTimesProto.internal_static_stoptimes_stopTimeCollection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StopTimesProto.stopTimeCollection.class, StopTimesProto.stopTimeCollection.Builder.class);
    }

    public static final int STOPTIMES_FIELD_NUMBER = 1;
    private java.util.List<StopTimesProto.StopTime> stopTimes_;
    /**
     * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
     */
    public java.util.List<StopTimesProto.StopTime> getStopTimesList() {
      return stopTimes_;
    }
    /**
     * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
     */
    public java.util.List<? extends StopTimesProto.StopTimeOrBuilder>
        getStopTimesOrBuilderList() {
      return stopTimes_;
    }
    /**
     * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
     */
    public int getStopTimesCount() {
      return stopTimes_.size();
    }
    /**
     * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
     */
    public StopTimesProto.StopTime getStopTimes(int index) {
      return stopTimes_.get(index);
    }
    /**
     * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
     */
    public StopTimesProto.StopTimeOrBuilder getStopTimesOrBuilder(
        int index) {
      return stopTimes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < stopTimes_.size(); i++) {
        output.writeMessage(1, stopTimes_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < stopTimes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, stopTimes_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof StopTimesProto.stopTimeCollection)) {
        return super.equals(obj);
      }
      StopTimesProto.stopTimeCollection other = (StopTimesProto.stopTimeCollection) obj;

      if (!getStopTimesList()
          .equals(other.getStopTimesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStopTimesCount() > 0) {
        hash = (37 * hash) + STOPTIMES_FIELD_NUMBER;
        hash = (53 * hash) + getStopTimesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static StopTimesProto.stopTimeCollection parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StopTimesProto.stopTimeCollection parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StopTimesProto.stopTimeCollection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StopTimesProto.stopTimeCollection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StopTimesProto.stopTimeCollection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StopTimesProto.stopTimeCollection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StopTimesProto.stopTimeCollection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StopTimesProto.stopTimeCollection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static StopTimesProto.stopTimeCollection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static StopTimesProto.stopTimeCollection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static StopTimesProto.stopTimeCollection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StopTimesProto.stopTimeCollection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(StopTimesProto.stopTimeCollection prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code stoptimes.stopTimeCollection}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:stoptimes.stopTimeCollection)
        StopTimesProto.stopTimeCollectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StopTimesProto.internal_static_stoptimes_stopTimeCollection_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StopTimesProto.internal_static_stoptimes_stopTimeCollection_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StopTimesProto.stopTimeCollection.class, StopTimesProto.stopTimeCollection.Builder.class);
      }

      // Construct using org.mobilitydata.gtfsproto.StopTimesProto.stopTimeCollection.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStopTimesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (stopTimesBuilder_ == null) {
          stopTimes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          stopTimesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StopTimesProto.internal_static_stoptimes_stopTimeCollection_descriptor;
      }

      @java.lang.Override
      public StopTimesProto.stopTimeCollection getDefaultInstanceForType() {
        return StopTimesProto.stopTimeCollection.getDefaultInstance();
      }

      @java.lang.Override
      public StopTimesProto.stopTimeCollection build() {
        StopTimesProto.stopTimeCollection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public StopTimesProto.stopTimeCollection buildPartial() {
        StopTimesProto.stopTimeCollection result = new StopTimesProto.stopTimeCollection(this);
        int from_bitField0_ = bitField0_;
        if (stopTimesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            stopTimes_ = java.util.Collections.unmodifiableList(stopTimes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.stopTimes_ = stopTimes_;
        } else {
          result.stopTimes_ = stopTimesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StopTimesProto.stopTimeCollection) {
          return mergeFrom((StopTimesProto.stopTimeCollection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(StopTimesProto.stopTimeCollection other) {
        if (other == StopTimesProto.stopTimeCollection.getDefaultInstance()) return this;
        if (stopTimesBuilder_ == null) {
          if (!other.stopTimes_.isEmpty()) {
            if (stopTimes_.isEmpty()) {
              stopTimes_ = other.stopTimes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStopTimesIsMutable();
              stopTimes_.addAll(other.stopTimes_);
            }
            onChanged();
          }
        } else {
          if (!other.stopTimes_.isEmpty()) {
            if (stopTimesBuilder_.isEmpty()) {
              stopTimesBuilder_.dispose();
              stopTimesBuilder_ = null;
              stopTimes_ = other.stopTimes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              stopTimesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStopTimesFieldBuilder() : null;
            } else {
              stopTimesBuilder_.addAllMessages(other.stopTimes_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        StopTimesProto.stopTimeCollection parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (StopTimesProto.stopTimeCollection) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<StopTimesProto.StopTime> stopTimes_ =
        java.util.Collections.emptyList();
      private void ensureStopTimesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          stopTimes_ = new java.util.ArrayList<StopTimesProto.StopTime>(stopTimes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          StopTimesProto.StopTime, StopTimesProto.StopTime.Builder, StopTimesProto.StopTimeOrBuilder> stopTimesBuilder_;

      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public java.util.List<StopTimesProto.StopTime> getStopTimesList() {
        if (stopTimesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(stopTimes_);
        } else {
          return stopTimesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public int getStopTimesCount() {
        if (stopTimesBuilder_ == null) {
          return stopTimes_.size();
        } else {
          return stopTimesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public StopTimesProto.StopTime getStopTimes(int index) {
        if (stopTimesBuilder_ == null) {
          return stopTimes_.get(index);
        } else {
          return stopTimesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public Builder setStopTimes(
          int index, StopTimesProto.StopTime value) {
        if (stopTimesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStopTimesIsMutable();
          stopTimes_.set(index, value);
          onChanged();
        } else {
          stopTimesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public Builder setStopTimes(
          int index, StopTimesProto.StopTime.Builder builderForValue) {
        if (stopTimesBuilder_ == null) {
          ensureStopTimesIsMutable();
          stopTimes_.set(index, builderForValue.build());
          onChanged();
        } else {
          stopTimesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public Builder addStopTimes(StopTimesProto.StopTime value) {
        if (stopTimesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStopTimesIsMutable();
          stopTimes_.add(value);
          onChanged();
        } else {
          stopTimesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public Builder addStopTimes(
          int index, StopTimesProto.StopTime value) {
        if (stopTimesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStopTimesIsMutable();
          stopTimes_.add(index, value);
          onChanged();
        } else {
          stopTimesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public Builder addStopTimes(
          StopTimesProto.StopTime.Builder builderForValue) {
        if (stopTimesBuilder_ == null) {
          ensureStopTimesIsMutable();
          stopTimes_.add(builderForValue.build());
          onChanged();
        } else {
          stopTimesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public Builder addStopTimes(
          int index, StopTimesProto.StopTime.Builder builderForValue) {
        if (stopTimesBuilder_ == null) {
          ensureStopTimesIsMutable();
          stopTimes_.add(index, builderForValue.build());
          onChanged();
        } else {
          stopTimesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public Builder addAllStopTimes(
          java.lang.Iterable<? extends StopTimesProto.StopTime> values) {
        if (stopTimesBuilder_ == null) {
          ensureStopTimesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, stopTimes_);
          onChanged();
        } else {
          stopTimesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public Builder clearStopTimes() {
        if (stopTimesBuilder_ == null) {
          stopTimes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          stopTimesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public Builder removeStopTimes(int index) {
        if (stopTimesBuilder_ == null) {
          ensureStopTimesIsMutable();
          stopTimes_.remove(index);
          onChanged();
        } else {
          stopTimesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public StopTimesProto.StopTime.Builder getStopTimesBuilder(
          int index) {
        return getStopTimesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public StopTimesProto.StopTimeOrBuilder getStopTimesOrBuilder(
          int index) {
        if (stopTimesBuilder_ == null) {
          return stopTimes_.get(index);  } else {
          return stopTimesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public java.util.List<? extends StopTimesProto.StopTimeOrBuilder>
           getStopTimesOrBuilderList() {
        if (stopTimesBuilder_ != null) {
          return stopTimesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(stopTimes_);
        }
      }
      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public StopTimesProto.StopTime.Builder addStopTimesBuilder() {
        return getStopTimesFieldBuilder().addBuilder(
            StopTimesProto.StopTime.getDefaultInstance());
      }
      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public StopTimesProto.StopTime.Builder addStopTimesBuilder(
          int index) {
        return getStopTimesFieldBuilder().addBuilder(
            index, StopTimesProto.StopTime.getDefaultInstance());
      }
      /**
       * <code>repeated .stoptimes.StopTime stopTimes = 1;</code>
       */
      public java.util.List<StopTimesProto.StopTime.Builder>
           getStopTimesBuilderList() {
        return getStopTimesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          StopTimesProto.StopTime, StopTimesProto.StopTime.Builder, StopTimesProto.StopTimeOrBuilder>
          getStopTimesFieldBuilder() {
        if (stopTimesBuilder_ == null) {
          stopTimesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              StopTimesProto.StopTime, StopTimesProto.StopTime.Builder, StopTimesProto.StopTimeOrBuilder>(
                  stopTimes_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          stopTimes_ = null;
        }
        return stopTimesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:stoptimes.stopTimeCollection)
    }

    // @@protoc_insertion_point(class_scope:stoptimes.stopTimeCollection)
    private static final StopTimesProto.stopTimeCollection DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StopTimesProto.stopTimeCollection();
    }

    public static StopTimesProto.stopTimeCollection getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<stopTimeCollection>
        PARSER = new com.google.protobuf.AbstractParser<stopTimeCollection>() {
      @java.lang.Override
      public stopTimeCollection parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new stopTimeCollection(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<stopTimeCollection> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<stopTimeCollection> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public StopTimesProto.stopTimeCollection getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stoptimes_StopTime_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stoptimes_StopTime_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stoptimes_stopTimeCollection_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stoptimes_stopTimeCollection_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020stop_times.proto\022\tstoptimes\"\306\003\n\010StopTi" +
      "me\022\017\n\007trip_id\030\001 \001(\t\022\024\n\014arrival_time\030\002 \001(" +
      "\t\022\026\n\016departure_time\030\003 \001(\t\022\017\n\007stop_id\030\004 \001" +
      "(\t\022\025\n\rstop_sequence\030\005 \001(\r\022\025\n\rstop_headsi" +
      "gn\030\006 \001(\t\022:\n\013pickup_type\030\007 \001(\0162%.stoptime" +
      "s.StopTime.PickupDropOffType\022<\n\rdrop_off" +
      "_type\030\010 \001(\0162%.stoptimes.StopTime.PickupD" +
      "ropOffType\022\033\n\023shape_dist_traveled\030\t \001(\002\022" +
      "4\n\ttimepoint\030\n \001(\0162!.stoptimes.StopTime." +
      "TimePrecision\"B\n\021PickupDropOffType\022\013\n\007RE" +
      "GULAR\020\000\022\010\n\004NONE\020\001\022\n\n\006AGENCY\020\002\022\n\n\006DRIVER\020" +
      "\003\"+\n\rTimePrecision\022\017\n\013APPROXIMATE\020\000\022\t\n\005E" +
      "XACT\020\001\"<\n\022stopTimeCollection\022&\n\tstopTime" +
      "s\030\001 \003(\0132\023.stoptimes.StopTimeB,\n\032org.mobi" +
      "litydata.gtfsprotoB\016StopTimesProtob\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_stoptimes_StopTime_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stoptimes_StopTime_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stoptimes_StopTime_descriptor,
        new java.lang.String[] { "TripId", "ArrivalTime", "DepartureTime", "StopId", "StopSequence", "StopHeadsign", "PickupType", "DropOffType", "ShapeDistTraveled", "Timepoint", });
    internal_static_stoptimes_stopTimeCollection_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stoptimes_stopTimeCollection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stoptimes_stopTimeCollection_descriptor,
        new java.lang.String[] { "StopTimes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
