/*
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.mobilitydata.gtfsvalidator.validator;

import static com.google.common.truth.Truth.assertThat;

import java.util.List;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;
import org.mobilitydata.gtfsvalidator.notice.NoticeContainer;
import org.mobilitydata.gtfsvalidator.notice.PointNearOriginNotice;
import org.mobilitydata.gtfsvalidator.notice.PointNearPoleNotice;
import org.mobilitydata.gtfsvalidator.notice.ValidationNotice;
import org.mobilitydata.gtfsvalidator.table.GtfsShape;

// FIXME: Cover autogenerated lat-lon validators by unit tests in "processor" (see issue #846).

@RunWith(JUnit4.class)
public class GtfsShapeLatLonValidatorTest {

  private static List<ValidationNotice> generateNotices(GtfsShape shape) {
    NoticeContainer noticeContainer = new NoticeContainer();
    new GtfsShapeLatLonValidator().validate(shape, noticeContainer);
    return noticeContainer.getValidationNotices();
  }

  @Test
  public void validPoint_yieldsNoNotice() {
    assertThat(
            generateNotices(
                new GtfsShape.Builder()
                    .setCsvRowNumber(2)
                    .setShapePtLat(45.0)
                    .setShapePtLon(45.0)
                    .build()))
        .isEmpty();
  }

  @Test
  public void origin_yieldsNotice() {
    assertThat(
            generateNotices(
                new GtfsShape.Builder()
                    .setCsvRowNumber(2)
                    .setShapePtLat(0.0)
                    .setShapePtLon(0.1)
                    .build()))
        .containsExactly(
            new PointNearOriginNotice("shapes.txt", 2, "shape_pt_lat", 0.0, "shape_pt_lon", 0.1));
  }

  @Test
  public void poles_yieldsNotice() {
    assertThat(
            generateNotices(
                new GtfsShape.Builder()
                    .setCsvRowNumber(2)
                    .setShapePtLat(90.0)
                    .setShapePtLon(0.0)
                    .build()))
        .containsExactly(
            new PointNearPoleNotice("shapes.txt", 2, "shape_pt_lat", 90.0, "shape_pt_lon", 0.0));

    assertThat(
            generateNotices(
                new GtfsShape.Builder()
                    .setCsvRowNumber(2)
                    .setShapePtLat(-90.0)
                    .setShapePtLon(0.0)
                    .build()))
        .containsExactly(
            new PointNearPoleNotice("shapes.txt", 2, "shape_pt_lat", -90.0, "shape_pt_lon", 0.0));
  }
}
