name: End to end 100

on:
  push:
    branches: [ master, extend-end-to-end ] #<-- replace transport-agency-name by the name of the agency/publisher

jobs:
  run-on-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare version name
        id: prep
        run: |
          VERSION_TAG=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION_TAG=-$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION_TAG=-pr-${{ github.event.number }}
          fi
          if [ ${VERSION_TAG} != ${GITHUB_REF#refs/tags/} ]; then
            VERSION_TAG=v${VERSION_TAG}-sha-${GITHUB_SHA::8}-SNAPSHOT
          fi
          echo ::set-output name=versionTag::${VERSION_TAG}
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Package cli app jar with Gradle
        uses: eskatos/gradle-command-action@v1
        env:
          versionTag: ${{ steps.prep.outputs.versionTag }}
        with:
          arguments: shadowJar
          
      - name: Validate dataset from -- Norway
        run: java -Xmx6G -Xms6G -jar main/build/libs/*.jar --url http://transitfeeds.com/p/norsk-reiseinformasjon-as/791/latest/download --output_base output --feed_name no-norway --storage_directory norway.zip
      - name: Validate dataset from -- IDFM (Paris, France)
        run: java -Xmx6G -Xms6G -jar main/build/libs/*.jar --url http://transitfeeds.com/p/ile-de-france-mobilite/1214/latest/download --output_base output --feed_name fr-idfm --storage_directory idfm.zip
      - name: Validate dataset from -- Colectivos (Buenos Aires, Argentina)
        run: java -Xmx6G -Xms6G -jar main/build/libs/*.jar --url http://transitfeeds.com/p/colectivos-buenos-aires/1037/latest/download --output_base output --feed_name ar-colectivos --storage_directory colectivos.zip
   
   #see https://github.com/MobilityData/gtfs-validator/pull/712#issuecomment-776110813
      - name: Validate dataset from -- Ruter (Oslo, Norway)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/ruter/240/latest/download --output_base output --feed_name no-ruter --storage_directory ruter.zip
      - name: Validate dataset from -- TAG (Grenoble, France)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/tag/594/latest/download --output_base output --feed_name fr-tag --storage_directory tag.zip
      - name: Validate dataset from -- Translink (Vancouver, Canada)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/translink-vancouver/29/latest/download --output_base output --feed_name ca-translink --storage_directory transkink.zip
      - name: Validate dataset from -- VAG (Freiburg, Germany)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/freiburger-verkehrs-ag/1228/latest/download --output_base output --feed_name de-vag --storage_directory vag.zip
      - name: Validate dataset from -- AC Transit (Oakland, CA, USA)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/ac-transit/1269/latest/download --output_base output --feed_name us-actransit --storage_directory actransit.zip
      - name: Validate dataset from -- AMT (Montreal, QC, Canada)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/agence-metropolitaine-de-transport/128/latest/download --output_base output --feed_name ca-amt --storage_directory amtmtl.zip
      - name: Validate dataset from -- Bay of Plenty Regional Council (Tauranga, New Zealand)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/bay-of-plenty-regional-council/1162/latest/download --output_base output --feed_name nz-bayplenty --storage_directory bayplenty.zip
      - name: Validate dataset from -- BHTRANS (Belo Horizonte, Brazil)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/bhtrans/640/latest/download --output_base output --feed_name br-bhtrans --storage_directory bhtrans.zip
      - name: Validate dataset from -- LYNX (Orlando, FL, USA)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/central-florida-regional-transportation-authority/373/latest/download --output_base output --feed_name us-lynx --storage_directory lynx.zip
      - name: Validate dataset from -- dBus (San Sebastián , Spain)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/compania-del-tranvia-de-san-sebastian/702/latest/download --output_base output --feed_name es-dbus --storage_directory dbus.zip
      - name: Validate dataset from -- Collegamenti marittimi Moby (Sardinia, Italy)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/collegamenti-marittimi-moby/1135/latest/download --output_base output --feed_name it-moby --storage_directory moby.zip
      - name: Validate dataset from -- Comboios de Portugal (Lisbon, Portugal)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/comboios-de-portugal/1004/latest/download --output_base output --feed_name pt-comboios --storage_directory comboios.zip
      - name: Validate dataset from -- Ferries (Finland)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/ferries/734/latest/download --output_base output --feed_name fi-ferries --storage_directory ferries.zip
      - name: Validate dataset from -- Maanteeamet (Estonia)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/maanteeamet/510/latest/download --output_base output --feed_name ee-maanteeamet --storage_directory maanteeamet.zip
      - name: Validate dataset from -- Nagaibus (Gunma, Japan)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/nagaibus/1212/latest/download --output_base output --feed_name jp-nagaibus --storage_directory nagaibus.zip
      - name: Validate dataset from -- MZDiK Radom (Radom, Poland)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/mzdik-radom/1008/latest/download --output_base output --feed_name pl-mzdik --storage_directory mzdik.zip
      - name: Validate dataset from -- MKV (Miskolc, Hungary)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/mvk-zrt/839/latest/download --output_base output --feed_name hu-mkv --storage_directory mkv.zip
      - name: Validate dataset from -- PTV (Melbourne, Australia)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/ptv/497/latest/download --output_base output --feed_name au-ptv --storage_directory ptv.zip
      - name: Validate dataset from -- Pays de la Loire (France)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/region-des-pays-de-la-loire/1071/latest/download --output_base output --feed_name fr-loire --storage_directory loire.zip
      - name: Validate dataset from -- RATP (Paris, France)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/regie-autonome-des-transports-parisiens/413/latest/download --output_base output --feed_name fr-ratp --storage_directory ratp.zip
      - name: Validate dataset from -- Semitan (Nantes, France)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/semitan/592/latest/download --output_base output --feed_name fr-semitan --storage_directory semitan.zip
      - name: Validate dataset from -- STIB-MIVB (Brussels, Belgium)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/societe-des-transports-intercommunaux-de-bruxelles/527/latest/download --output_base output --feed_name be-stibmivb --storage_directory stibmivb.zip
      - name: Validate dataset from -- STO (Gatineau, QC, Canada)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/societe-de-transport-de-loutaouais/828/latest/download --output_base output --feed_name ca-sto --storage_directory sto.zip
      - name: Validate dataset from -- TrafikLab (Sweden)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/trafiklab/50/latest/download --output_base output --feed_name se-trafiklab --storage_directory trafiklab.zip
        
      - name: Validate dataset from -- Amtrak (USA)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/amtrak/1136/latest/download --output_base output --feed_name us-amtrak --storage_directory amtrak.zip
      - name: Validate dataset from -- ATOC (United Kingdom)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/association-of-train-operating-companies/284/latest/download --output_base output --feed_name uk-atoc --storage_directory atoc.zip
      - name: Validate dataset from -- ART (Arlington, VA, USA)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/arlington-transit/149/latest/download --output_base output --feed_name us-art --storage_directory art.zip
      - name: Validate dataset from -- Bustang (Denver, CO, USA)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/bustang/770/latest/download --output_base output --feed_name us-bustang --storage_directory bustang.zip
      - name: Validate dataset from -- Capital Metro (Austin, TX, USA)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/capital-metro/24/latest/download --output_base output --feed_name us-capitalmetro --storage_directory capitalmetro.zip
      - name: Validate dataset from -- Bus It Waikato (Waikato District, New Zealand)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/bus-it-waikato/1226/latest/download --output_base output --feed_name nz-busit --storage_directory busit.zip
      - name: Validate dataset from -- City of Kuopio (Kuopio, Finland)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/city-of-kuopio/731/latest/download --output_base output --feed_name fi-kuopio --storage_directory kuopio.zip
      - name: Validate dataset from -- Transit Windsor (Windsor, Canada)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/city-of-windsor/778/latest/download --output_base output --feed_name ca-windsor --storage_directory windsor.zip
      - name: Validate dataset from -- Santiago DPTM (Santiago, Chile)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/dtpm-santiago-santiago/972/latest/download --output_base output --feed_name cl-dptm --storage_directory dptm.zip
      - name: Validate dataset from -- EMT Madrid (Madrid , Spain)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/emt-madrid/212/latest/download --output_base output --feed_name es-emtmd --storage_directory emtmd.zip
      - name: Validate dataset from -- EMT Valencia (Valencia, Spain)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/emt-valencia/719/latest/download --output_base output --feed_name es-emtva --storage_directory emtva.zip
      - name: Validate dataset from -- Entur (Entur, Norway)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/entur/970/latest/download --output_base output --feed_name no-entur --storage_directory entur.zip
      - name: Validate dataset from -- CityBus (Lafayette, IN, USA)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/greater-lafayette-public-transportation-corporation-citybus/1131/latest/download --output_base output --feed_name us-citybus --storage_directory citybus.zip
      - name: Validate dataset from -- Gruppo Torinese Trasporti (Turin, Italy)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/gruppo-torinese-trasporti/51/latest/download --output_base output --feed_name it-gtt --storage_directory gtt.zip
      - name: Validate dataset from -- HSL (Helsinki, Finland)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/helsinki-regional-transport/735/latest/download --output_base output --feed_name fi-hsl --storage_directory hsl.zip
      - name: Validate dataset from -- MVTA (Minneapolis, MN, USA)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/minnesota-valley-transit-authority/177/latest/download --output_base output --feed_name us-mvta --storage_directory mvta.zip
      - name: Validate dataset from -- Praha (Prague, Czech Republic)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/praha/801/latest/download --output_base output --feed_name cz-praha --storage_directory praha.zip
      - name: Validate dataset from -- PID (Prague, Czech Republic)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/prazska-integrovana-doprava/1106/latest/download --output_base output --feed_name cz-pid --storage_directory pid.zip
      - name: Validate dataset from -- Saint Petersburg (Saint Petersburg, Russina federation)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/saint-petersburg/826/latest/download --output_base output --feed_name ru-stpetersburg --storage_directory stpetersburg.zip
      - name: Validate dataset from -- RCT (Vermont, USA)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/rural-community-transportation/563/latest/download --output_base output --feed_name us-rct --storage_directory rct.zip
      - name: Validate dataset from -- STIF (Paris, France)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/stif/822/latest/download --output_base output --feed_name fr-stif --storage_directory stif.zip
      - name: Validate dataset from -- SulFertagus (Lisbon, Portugal)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/sulfertagus/1005/latest/download --output_base output --feed_name pt-fertagus --storage_directory fertagus.zip
      - name: Validate dataset from -- Changhua (Changhua County, Taiwan, Republic of China)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/taiwan/956/latest/download --output_base output --feed_name tw-changhua --storage_directory changhua.zip
      - name: Validate dataset from -- Nantou (Nantou County, Taiwan, Republic of China)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/taiwan/958/latest/download --output_base output --feed_name tw-nantou --storage_directory nantou.zip
      - name: Validate dataset from -- Miaoli (Miaoli County, Taiwan, Republic of China)
        run: java -jar main/build/libs/*.jar --url http://transitfeeds.com/p/taiwan/954/latest/download --output_base output --feed_name tw-miaoli --storage_directory miaoli.zip

      - name: Persist datasets
        uses: actions/upload-artifact@v2
        with:
          name: dataset_all
          path: ./*.zip
      - name: Persist reports
        uses: actions/upload-artifact@v2
        with:
          name: validation_report_all
          path: output
