name: Publish Jars Snapshots

on:
  push:
    branches: [ 146-Migrate-maven-repository ]
    paths-ignore:
      - '**.md'
      - '**.py'
      - 'Dockerfile'
      - '.gitignore'
      - 'LICENSE'
      - 'docker.yml'
      - 'formatting.yml'
      - 'test_pack_dock.yml'
      - 'triage.yml'
      - 'acceptance_test.yml'
      - 'web/**'
  workflow_dispatch:

env:
  java_version: '17'
  java_distribution: 'zulu'

jobs:
  publish-snapshots:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # We need to download all tags so that the axion-release-plugin
          # can resolve the most recent version tag.
          fetch-depth: 0

      - name: Set up JDK ${{ env.java_version }}-${{ env.java_distribution }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.java_version }}
          distribution: ${{ env.java_distribution }}

      # The following steps will publish artifacts to a sonatype staging repo with the aim of promoting them to maven central
      # Pretty much everything is done through gradle.
      # The version used will be according to the axion-release-plugin, meaning it will take a tag if present.
      # The tag should follow semantic versioning, e.g. v1.2.3. There could be a suffix, e.g. v1.2.3-TEST
      # gradle will build, sign then upload artifacts to a Sonatype staging repo.
      # See https://s01.oss.sonatype.org for accessing these repos.
      # At this point it should manually be closed, which will trigger acceptance tests for maven central (but not transfer yet)
      # Once closed, the repo is available for testing.
      # After testing, it can be manually promoted on the sonatype site, which will then publish to maven central.
      # Note than once in maven central a release cannot be removed or altered.

      - name: Load secrets from 1Password
        id: onepw_secrets
        uses: ./.github/actions/extract-1password-secret
        with:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }} # This is required to connect to the vault in our 1Password account.
          VARIABLES_TO_EXTRACT: 'MAVEN_GPG_PASSPHRASE, MAVEN_GPG_PRIVATE_KEY, MAVEN_CENTRAL_PORTAL_TOKEN_USERNAME, MAVEN_CENTRAL_PORTAL_TOKEN_PASSWORD'
          ONE_PASSWORD_SECRET_REFERENCES: ${{ vars.ONE_PASSWORD_SECRET_REFERENCES }}

      - name: Build and Publish to Sonatype
        run: |
          ./gradlew publish --rerun-tasks --info

