name: Upload Release Assets

on:
  push:
    branches: [ 1588-publish-to-maven-central ]
#  release:
#    types: [ prereleased, released ]

jobs:
  build-jars:
    runs-on: ubuntu-latest

    steps:
    
      - name: Load secrets from 1Password
        id: onepw_secrets
        uses: 1password/load-secrets-action@v1.3.1
        with:
            export-env: true # Export loaded secrets as environment variables
        env:
            OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }} # This is required to connect to the vault in our 1Password account.
            MAVEN_GPG_PRIVATE_KEY: "op://rbiv7rvkkrsdlpcrz3bmv7nmcu/yztcx47yzp4vizjyaq7ulvkgoi/Private key"
            MAVEN_GPG_PASSPHRASE: "op://rbiv7rvkkrsdlpcrz3bmv7nmcu/yztcx47yzp4vizjyaq7ulvkgoi/password"
            SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
            SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}


#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'zulu'
#

      - name: Modify the private key format
        run: |
          # The key obtained fro 1password is flattened, i.e. its on one line. Put it back as multiline
          header="-----BEGIN PGP PRIVATE KEY BLOCK-----"
          footer="-----END PGP PRIVATE KEY BLOCK-----"
          
          # Extract the content between the header and footer
          content=$(echo "$MAVEN_GPG_PRIVATE_KEY" | sed -e "s/^${header}//" -e "s/${footer}$//")
          
          # Replace spaces in the content with newlines
          converted_content=$(echo "$content" | tr ' ' '\n')
          
          # Combine everything into the complete key
          echo "$header" > restored_key.asc
          echo "$converted_content" >> restored_key.asc
          echo "$footer" >> restored_key.asc
          
          # Output the combined values to a file that we can then use to import in the temporary GPG keyring
          echo -e "$header\n$converted_content\n$footer" > gpg_private_key.asc


      - name: Import GPG key
        run: |
          echo "modified key"
          cat gpg_private_key.asc
          echo "modified key end"
          gpg --batch --import gpg_private_key.asc
          gpg --list-keys
#
#      - name: Build and Publish
#        run: ./gradlew publish

#      - name: Print trucs
#        run: |
#          echo "Hello World!"
#          echo "truc1"
#          echo $MAVEN_GPG_PASSPHRASE
#          echo "truc2"
#          echo $MAVEN_GPG_PRIVATE_KEY


