name: secret-refs
on:
  push:
    branches: [ 146-Migrate-maven-repository ]
  workflow_dispatch:

jobs:
  my-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load secrets from 1Password
        id: onepw_secrets
        uses: ./.github/actions/extract-1password-secret
        with:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }} # This is required to connect to the vault in our 1Password account.
          VARIABLES_TO_EXTRACT: 'MAVEN_GPG_PASSPHRASE, MAVEN_GPG_PRIVATE_KEY, SONATYPE_TOKEN_USERNAME, SONATYPE_TOKEN_PASSWORD'
          ONE_PASSWORD_SECRET_REFERENCES: ${{ vars.ONE_PASSWORD_SECRET_REFERENCES }}

      - name: Use extracted value
        run: |
          MAVEN_GPG_PASSPHRASE = echo $MAVEN_GPG_PASSPHRASE | sed 's/./&./g'
          MAVEN_GPG_PRIVATE_KEY = echo $MAVEN_GPG_PRIVATE_KEY | sed 's/./&./g'
          echo "The value for the MAVEN_GPG_PASSPHRASE is \"$MAVEN_GPG_PASSPHRASE\""
          echo "The value for the MAVEN_GPG_PRIVATE_KEY is \"$MAVEN_GPG_PRIVATE_KEY\""
