name: secret-refs
on:
  push:
    branches: [ 1906-publishing-maven-package-github-action-is-failing ]
  workflow_dispatch:

jobs:
  my-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract value
        id: extract_value
        uses: ./.github/actions/extract-1password-secret
        with:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }} # This is required to connect to the vault in our 1Password account.
          keys: 'MAVEN_GPG_PASSPHRASE qaz'
          ONE_PASSWORD_SECRET_REFERENCES: ${{ vars.ONE_PASSWORD_SECRET_REFERENCES }}

      - name: Use extracted value
        run: |
          echo "The value for the MAVEN_GPG_PASSPHRASE is ${{ env.MAVEN_GPG_PASSPHRASE }}"
          echo "The value for the qaz is ${{ env.qaz }}"