name: Web client staging CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_VERSION: "20"

jobs:

  web_cd:
    name: Deploy web client
    runs-on: ubuntu-latest

    env:
      ENV_NAME              : stg
      CLOUDSDK_CORE_PROJECT : web-based-gtfs-validator

    steps:

      - uses: actions/checkout@v4
        with:
          # We need to download all tags so that the axion-release-plugin
          # can resolve the most recent version tag.
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          # We need a recent version of Java with jpackage included.
          java-version: '17'
          # We use the zulu distribution, which is an OpenJDK distro.
          distribution: 'zulu'

      # for npm
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_WEB_VALIDATOR_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 390.0.0'

      - name: run gradle tasks
        shell: bash
        run: |
          ENV_FILE=web/pipeline/${ENV_NAME}.env source web/pipeline/env-file.sh
          ./gradlew ':web:client:webDeploy'
