name: Bug triage
on:
  issues:
    types:
      - opened
jobs:
  triage:
    if: github.event.issue.labels.contains("bug")
    runs-on: ubuntu-latest
    steps:
      - name: Create card
        uses: alex-page/github-project-automation-plus@v0.8.2
        with:
          project: Bug triage
          column: Requires investigation
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment issue
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thank you for your reporting a bug. The issue has been placed in [triage](https://github.com/orgs/MobilityData/projects/60/views/1), the MobilityData team will follow-up on it."
            })
