name: Bug triage
on:
  issues:
    types:
      - labeled
jobs:
  triage:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Bug triage
          column: Requires investigation
          repo-token: ${{ secrets.TRIAGE_TOKEN }}
