name: Web service CI

on:
  pull_request:
    branches:
      - master
    paths:
      - 'web/service/**'

env:
    NODE_VERSION: "20"
    java_version: '17.0'
    java_distribution: 'zulu'

jobs:

  web_ci:
    name: Build web service
    runs-on: ubuntu-latest

    env:
      ENV_NAME              : prd
      CLOUDSDK_CORE_PROJECT : web-based-gtfs-validator

    steps:

      - uses: actions/checkout@v4
        with:
          # We need to download all tags so that the axion-release-plugin
          # can resolve the most recent version tag.
          fetch-depth: 0

      - name: Set up JDK ${{ env.java_version }}-${{ env.java_distribution }}
        uses: actions/setup-java@v4
        with:
          # We need a recent version of Java with jpackage included.
          java-version: ${{ env.java_version }}
          # We use the zulu distribution, which is an OpenJDK distro.
          distribution: ${{ env.java_distribution }}

      # for npm
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_WEB_VALIDATOR_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 390.0.0'

      - name: run gradle tasks
        shell: bash
        run: |
          ENV_FILE=web/pipeline/${ENV_NAME}.env source web/pipeline/env-file.sh
          ./gradlew ':web:service:webTest' ':web:service:webBuild'
