name: Web client Cypress e2e tests

on:
  pull_request:
      branches: [ master ]
      paths:
        - 'web/client/**'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: web/client

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npx vite --config vite.config-cypress.js
          wait-on: "npx wait-on --timeout 2000 http://127.0.0.1:5173"
          working-directory: web/client

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: web/client/cypress/screenshots

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: web/client/cypress/videos
