name: Web client Cypress e2e tests

on:
  pull_request:
      branches: [ master ]
      paths:
        - 'web/client/**'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npx vite --host 127.0.0.1 --port 5173
          wait-on: "npx wait-on --timeout 120000 http://127.0.0.1:5173"
          working-directory: ./web/client
